### ISSUE TITLE
Runtime Error: Already started in multiprocess

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1443] opened 2019-05-20 17:24 UTC
@xtyDoge commented on [Sat May 18 2019](https://github.com/microsoft/vscode-python/issues/5679)

## Environment data

- VS Code version: 1.34.0
- Extension version (available under the Extensions sidebar): 2019.4.12954
- OS and version: macOS 10.14.4
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.5
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A

## Actual behaviour

When I try to use the "multiprocessing" module to start a new processing like
`p = multiprocessing.Process(target=func)`
`p.start()`
And it will raise an exception like
```
E00000.247: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/Users/mac/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/Users/mac/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/Users/mac/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
                return next(self.gen)
              File "/Users/mac/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/Users/mac/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
```
But When I try to execute it in terminal instead, I will get the right output

**Comment by karthiknadig** [comment] 2019-05-20 17:30
@xtyDoge Try following these instructions to get multi-process debugging working on mac:
https://github.com/microsoft/ptvsd/blob/master/TROUBLESHOOTING.md#1-multiprocessing-on-linuxmac

**Comment by amittleider** [comment] 2019-05-29 11:19
On Ubuntu, putting this at the top of the main entrypoint file worked for me:

```
import multiprocessing
multiprocessing.set_start_method('spawn', True)
```

**Comment by amirhfarzaneh** [comment] 2019-06-07 05:02
I didn't have this problem until vscode updated to 1.35 today!

**Comment by CAH-FlyChen** [comment] 2019-06-17 02:03
i got the same issue.
when i change to multiprocessing.set_start_method('spawn', True),
got
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'register.<locals>._handler'

**Comment by karthiknadig** [comment] 2019-06-27 20:44
@CAH-FlyChen See this for help on how to handle this case: https://github.com/microsoft/ptvsd/issues/1283#issuecomment-501127755

Closing this issue. The tracking issue for this issue is https://github.com/Microsoft/ptvsd/issues/943

**Closed by karthiknadig** 2019-06-27 20:44 UTC
Labels: Investigate

**Comment by civilman628** [comment] 2019-09-10 23:08
I add these 2 lines above, but the issue is still there.


E00032.889: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/home/mingming/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/home/mingming/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/home/mingming/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
                return next(self.gen)
              File "/home/mingming/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/home/mingming/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Traceback (most recent call last):

**Comment by karthiknadig** [comment] 2019-09-11 14:17
@civilman628 Create a new bug, if possible share your code. Also share the launch.json config that you are using.
