### ISSUE TITLE
Debugging opens new all-lowercase file

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1313] opened 2019-04-04 21:21 UTC
@whubbla commented on [Mon Apr 01 2019](https://github.com/Microsoft/vscode-python/issues/5049)

Issue Type: <b>Bug</b>

When I open a .py file, and set a breakpoint of StopOnEntry=True in launch.json, and start debugging, as soon as a breakpoint or initial stop is hit (or there's a runtime error), another tab opens with an all-lowercase version of the filename (it previously was a mix of lower and upper-case).

So, I then have two tabs, MyScript.py and myscript.py.  The debugger is active in myscript.py, even though I started it from MyScript.py.

I hover over the original one (MyScript.py), and it says something like (capitalization pattern reproduced here): "Q:\Myname\GitHub\FolderPath\SubPath123\Othername\MyScript.py"

If I hover over the all-lowercase file, it shows this:
"Q:\Myname\GitHub\folderpath\subpath123\Othername\myscript.py"

So, it changes the case in folderpath and subpath123 and myscript, but not in Othername.

It still saves to the proper filename, but it gets confusing in the code editor.

I'm using "Python: Current File (Integrated Terminal)" and it looks like this:

    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "stopOnEntry": true,
            "console": "integratedTerminal"
        },

Extension version: 2019.3.6215
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|31.65GB (24.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

---

@fr43nk commented on [Tue Apr 02 2019](https://github.com/Microsoft/vscode-python/issues/5049#issuecomment-478925598)

Can confirm this behavior. Set a breakpoint in the python file. When debugging, the file is reopened with a lower case name. This is no problem as long as the open tab is not static (i.e. edited the file) so the tab can be replaced with the "new" file with the name all in lower case.

VSCode: 1.32.3
Python extension: 2019.3.6215 (28 March 2019)
OS: Win7

---

@DonJayamanne commented on [Thu Apr 04 2019](https://github.com/Microsoft/vscode-python/issues/5049#issuecomment-480008111)

Please could you do the following:
* Open VS Code
* Select the command `Extensions: Open Extensions Folder`
* Locate the Python extension directory, typically of the form `ms-python.python-2019.3.****`
* In that directory ensure you do not have any `debug*.log` files, if you do, please delete them
* Go back into VS Code and modify your `launch.json` to add the setting `"logToFile": true`, see below:
```js
"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "logToFile": true
    },
```
* Start debugging
* When done (when you get the duplicate window opened), then
    * Go back into the extension directory
    * Upload the file `debug*.log` into this GitHub issue

---

@whubbla commented on [Thu Apr 04 2019](https://github.com/Microsoft/vscode-python/issues/5049#issuecomment-480067721)

Here you go.  I tried to replicate the issue with more generic folder names (it replicated in the sense that the debugger opened another tab and messed with the capitalization in the file path, but the .py file itself didn't have its capitalization affected).  So, this is the log from the original issue.
[debug15860.log](https://github.com/Microsoft/vscode-python/files/3045527/debug15860.log)

**Comment by DonJayamanne** [comment] 2019-04-04 21:22
@karthiknadig @int19h 
Please check the logs, as you can see the data sent from VSC to the PTVSD contains the correct case, however when PTVSD replies back with the stack trace the case of the paths is changed, hence the issue.

**Comment by int19h** [comment] 2019-04-04 21:57
We do path case normalization, which on Windows has this effect. But the path is equivalent, in a sense that it still refers to the same exact file - VSC shouldn't treat it as distinct file, and should just show the existing tab for it, like VS does. As it is, it looks like VSC editor is not respecting pathname case-insensitivity on Windows at all, and I would argue that it's a bug.

Note that this would still be a problem in attach scenarios even without forced case normalization, since many paths reported by Python are derived from user-specified ones, and any case discrepancies in that would still affect VSC. For example, suppose I have a file named `C:\Temp\test.py` - if I run it with `python c:\temp\test.py` (note the case), and print `__file__`, it will also say `c:\temp\test.py`, and it will be reported as such by the debugger. The workaround is to always specify the paths proper-cased, but this is not a normal expectation for any Windows app.

**Comment by DonJayamanne** [comment] 2019-04-04 22:39
> We do path case normalization, which on Windows has this effect. But the path is equivalent, in a sense that it still refers to the same exact file - VSC shouldn't treat it as distinct file, and should just show the existing tab for it, like VS does. As it is, it looks like VSC editor is not respecting pathname case-insensitivity on Windows at all, and I would argue that it's a bug.

Agreed, lets discuss with VSC. I've got a meta issue (https://github.com/Microsoft/vscode-python/issues/2976) going with issues related to path mappings and the like.

**Comment by fabioz** [comment] 2019-04-08 14:08
Actually, the debugger tries to provide the path with the proper case back to VSCode (so, I'd like to get more info here)...

@whubbla, can you answer some things for me to try to diagnose why that's not working there? (I've tried changing the filename cases here and it seems to work for me and open the file with the correct case, even when the `.pyc` becomes stale and has a different case, so, probably there's something different on my side).

1. What's the Python version you're using?

2. What's the case seem by Windows Explorer for that file (i.e.: right-click file in VSCode > Reveal in Explorer, copy path from there + filename with the path seen there).

3. What's the path copied from VSCode? (right-click file in VSCode > Copy Path).

4. If you change your that file to have the contents below and run it under the debugger, what's the output you have?

```
print('__file__ is: %s' % (__file__,))
import pydevd_file_utils
print('norm_file_to_client: %s' % (pydevd_file_utils.norm_file_to_client(__file__)),)
```

5. I see you have a `q:` in your log... is this some network mapped path you have?

6. Do you know if you changed some setting in your machine related to long paths/short paths on Windows?

@int19h although the debugger has paths normalized internally, it tries to send the real path back to VSCode later on... so, I'm curious, are you able to reproduce that in your machine? -- I haven't been able to reproduce it here (even when the `.pyc` content is stale as it seems to properly get the correct case later on for me -- the one case I think it could become wrong is with path mappings, but it doesn't seem to be the case here).

i.e.: 
When sending a file from the debugger to the client, in:

`_original_file_to_client`:
https://github.com/Microsoft/ptvsd/blob/master/src/ptvsd/_vendored/pydevd/pydevd_file_utils.py#L392

it should use
`_get_path_with_real_case`
https://github.com/Microsoft/ptvsd/blob/master/src/ptvsd/_vendored/pydevd/pydevd_file_utils.py#L133

So, I'm a bit puzzled on why that's not working...

**Comment by whubbla** [comment] 2019-04-08 15:50
@fabioz - 

1. 3.7.1, build h8c8aaf0_6 from Anaconda
2. Q:\Jimmy\GitHub\GlobalData\EuropeCY2018\Sam\NationalSAMs.py
3. Q:\Jimmy\GitHub\GlobalData\EuropeCY2018\Sam\NationalSAMs.py
4. __file__ is: q:\Jimmy\GitHub\GlobalData\EuropeCY2018\Sam\NationalSAMs.py
norm_file_to_client: Q:\Jimmy\GitHub\globaldata\europecy2018\Sam\nationalsams.py
5. Yes, it is mapped to an Amazon EC2 location, which looks something like \\ec2-name.domain.local
6. No, haven't changed anything.  Using Server 2019.

**Comment by fabioz** [comment] 2019-04-08 16:24
It seems that the problem is that the approach to get the real path (converting to a short path name and then back to a long path name) does not work properly with mapped paths (strangely some parts are correct and some are not).

I think the debugger could use a different method to determine the real path in this case (previously `ptvsd` used a different algorithm using `glob` to do that instead of short/long pathnames: https://github.com/Microsoft/ptvsd/blob/5197e1e73f1cc06a3738f88e84e026b3ef9b9efb/ptvsd/pathutils.py#L41 -- I think that it may be a reasonable alternative in this case... using `glob` over a network is probably not ideal, but that should only happen for files actually sent to the client and the result is cached afterwards).

@int19h @DonJayamanne 
let me know what you think (do you think it switch for the `glob` method or should this be handled in VSCode itself?)

**Comment by int19h** [comment] 2019-04-08 20:41
We're going to discuss it with VSC.

Side note: the underlying issue doesn't even require debugging to repro. Try this on Windows from command line:
```
code test.py
code Test.py
```
it opens two different tabs!

**Comment by fabioz** [comment] 2019-04-10 17:34
As a note, the fix on the `ptvsd` side is being handled on: https://github.com/Microsoft/ptvsd/issues/1330 (not sure if this one should be closed or not).

**Comment by DonJayamanne** [comment] 2019-04-10 20:04
You could also close #1330 instead. Up to you how you want to track your issues/work. I filled that as a reminder/request for a change/temp work around for this issue.

**Comment by fabioz** [comment] 2019-04-15 16:48
This should be fixed in master (in the `ptvsd` side) by https://github.com/Microsoft/ptvsd/commit/69a76244bf3a3780d8f25dbc4f8adf346aa0692a.

**Closed by fabioz** 2019-04-15 16:48 UTC
Labels: Bug, Regression, Unplanned-work, Upstream-pydevd, priority:P0
