### ISSUE TITLE
Capture Performance Telemetry

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#39] opened 2018-02-05 22:37 UTC
In the recent release of VS Code we introduced some changes to capture some telemetry on the performance of the debugger, specifically:
* How long it takes to launch the debugger
* How long it takes for the debugger to break after executing the following commands `stepIn`, `stepOut`, `continue`, `next`

Now, I don't see any code in PTVSD to capture telemetry. Thats fine.
The problem is we'll need this, without this we cannot measure the performance improvements (and this is a must for the first release).

So the question is:
* Who'll add this telemetry? PTVSD (debugger) or the adapter (the stuff in the middle) layer?
If this is something we're going to need for VS as well, then it must be done in PTVS.

**Comment by DonJayamanne** [comment] 2019-08-15 22:14
@int19h @karthiknadig 
Please could you add this telemetry. We'll need this to determine whether shipping the wheels does impact improve performance or not & by how much.

Telemetry for: Time to start debugger, etc.
Obviously we'll need this to compare perf for debugging with & without wheels.

**Comment by int19h** [comment] 2019-08-16 00:54
We need to identify a specific list of metrics.

And some of these will need to be implemented on VSCode side - e.g. time to start the debugger has to be measured on that side, because it includes the process spawn time, which cannot be measured by the process itself. VSCode could measure it by starting a timer when debug session starts, and stopping it when it sees the first "thread" event - this is the most reliable indicator that user code has started running in the debuggee process.

However, binary wheels also affect the execution of user code by improving tracing performance, so we also need to measure that somehow. We could measure the total time spent in user code - i.e. time during which the process isn't paused. But the problem is that for any app that blocks while running (e.g. reads input, or listens for socket connection, or waits for a lock etc), our measurements will include those blocking waits, which will dominate perf.

Then we need to consider multithreading, given that some threads might be paused while others are running, and that GIL really only allows one thread running at a time.

This all needs to be very carefully designed for us to get any meaningful data out of this, and it won't be trivial to implement. We might want to do some manual perf testing first, on specifically written test code with various patterns (which can measure itself with the `time` module), to see how much telemetry we still need after getting the numbers from that.

**Comment by int19h** [comment] 2019-08-16 00:57
One other thing. Our logs already have high-resolution timestamps on every event, which start counting from the moment logging is initialized (which happens right after we parse the command line).

So if you capture a full log, you can see how long the entire debug session took from debugger's perspective, and you can see how long individual events took by comparing timestamps for messages.

For example, to measure a step, you can look at the timestamp for the "stepIn" request, and the timestamp for the "stopped" event that followed - this will correspond pretty closely to the delay observed by the user in the UI.

**Comment by DonJayamanne** [comment] 2019-08-16 01:20
> So if you capture a full log, you can see how long the entire debug session took from debugger's perspective, and you can see how long individual events took by comparing timestamps for messages

Yes this is possible. However the metrics are for the PM team.
Best discussed separately. I.e. build a tool to extract and compare the values or capture the metrics via debugger telemetry events (and use existing tools).

**Comment by fabioz** [comment] 2019-08-16 11:29
As a note, I do have some performance numbers on some scenarios (which I
usually rerun when I do changes I think will affect performance).

It has numbers for the regular run (without compiled speedups), a run with
only cython and a run with cython+frame eval on the scenarios where I think
that the debugger is affected most -- the usual problem for the debugger is
deciding fast whether to not trace a method or if it has to trace how fast
a line is handled to hit some breakpoint or doing a step.

The numbers are committed in the repository:
https://github.com/microsoft/ptvsd/blob/master/src/ptvsd/_vendored/pydevd/tests_python/performance_check.py#L193

As for getting numbers from the telemetry on user machines, I think that
the startup time is a reasonable metric, but apart from that, the times for
a user machine would vary too much based on what the user/program is doing,
so, I'm not sure how useful such a metric would be (it'd be nice to have an
explanation on what exactly the PM team wants from this telemetry to check
how to produce numbers that actually match that expectation).

**Comment by Anapo14** [comment] 2019-08-16 16:20
Of course having an exact measure of what the user is doing would be ideal. Don and I spoke about this yesterday...for example, if they  have some kind of 'sleep' within their code (as just an example), that could muddy the waters, but from a reporting standpoint, as long as we are averaging what is happening across all users I think we should be fine. @DonJayamanne mentioned that this was done in the past. Please let me know if I didn't summarize that correctly, Don. 

I think a reasonable first pass is to use existing tools, come to an agreement on what we want to measure, and get it in...unless building the more 'accurate' tool can be done in a reasonable amount of time. I can speak with @qubitron about this next week.

**Closed as completed** 2019-09-12 18:31 UTC
Labels: Enhancement
