### ISSUE TITLE
New multiprocessing.Process sometimes hangs without starting

### ISSUE THREAD

**Issue by azertyfun** [Microsoft/ptvsd#1099] opened 2019-01-15 10:31 UTC
## Environment data

- PTVSD version: 4.2.0
- OS and version: Arch Linux with 4.20.0 kernel (client), Ubuntu 18.04 LXC (remote)
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.15 (could not reproduce on python 3)
- Using VS Code or Visual Studio: VS Code 1.30.2

## Actual behavior

When starting a bunch of `Process` objects, some of them never actually start. Instead, the hang with `process.is_alive() == True` but never reaching the target function.

## Expected  behavior

All `Process` objects reach the target function.

## Steps to reproduce:
1. Run [this file](https://gist.github.com/azertyfun/898f1ae245f5c3dce9840355cf8ae395) on the remote using python 2;
2. Attach using VSCode on port 5678;
3. After all processes have been created, it is likely that some of them never exit (you may have to retry a few times, as it may be harder to reproduce with a machine more powerful than mine).

**Comment by karthiknadig** [comment] 2019-01-22 17:09
2.7 uses `os.fork` on linux which is not yet supported by the debugger. see https://github.com/Microsoft/ptvsd/issues/943

**Comment by karthiknadig** [comment] 2019-01-23 21:57
Closing this as dupe of #943

**Closed by karthiknadig** 2019-01-23 21:57 UTC
