### ISSUE TITLE
gevent setting does not fix debugging code using gevent

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1773] opened 2019-09-15 07:47 UTC
@picklit commented on [Sun Sep 15 2019](https://github.com/microsoft/vscode-python/issues/7401)

## Environment data

- VS Code version: 1.38.0
- Extension version (available under the Extensions sidebar): 2019.9.34911
- OS and version: Ubuntu 18.04.3 LTS (4.4.0-18362-Microsoft x86_64)
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): n/a
- Relevant/affected Python packages and their versions: locustio 0.11.1
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): false

## Expected behaviour

Expect Python debugger to run the application and stop at a breakpoint.  Also, expect to be able to pause an executing Python thread. 

## Actual behaviour

Any code that imports locust hangs in the debugger.  It never hits a breakpoint and it is not possible to pause the threads.  Instead the program hangs somewhere during the package initialization and never gets to the first statement of the python file being debugged.

## Steps to reproduce:

This small piece of python code reproduces the problem. The print() statement is never executed:

```
import locust

if __name__== "__main__":
    print("debugger never reaches this breakpoint.")
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

no output

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
cd /home/mark/projects/load ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 GEVENT_SUPPORT=True /usr/bin/python3 /home/mark/.vscode-server/extensions/ms-python.python-2019.9.34911/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 55611 /home/mark/projects/load/min.py 
```

---

@picklit commented on [Sun Sep 15 2019](https://github.com/microsoft/vscode-python/issues/7401#issuecomment-531537344)

Here is the debug launch configuration I'm using

    {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "console": "integratedTerminal",
        "gevent": true
    },
:::

---

@DonJayamanne commented on [Sun Sep 15 2019](https://github.com/microsoft/vscode-python/issues/7401#issuecomment-531543155)

Thanks for reporting this issue. As this is related to the debugger I'm closing this issue here and copying it over to the corresponding debugger repo.
Please be assured, we will address this issue in that repo.

**Comment by karthiknadig** [comment] 2019-09-16 06:32
@picklit Can you try adding `"justMyCode": false,` in your launch json? It might reveal some additional info.

You can enable debugger logging using the following environment variables:
```
PTVSD_LOG_DIR=/home/user/logs
PYDEVD_DEBUG=True
PYDEVD_DEBUG_FILE=/home/user/logs/pydevd.log
```
These can be set using "env" files in the launch json. Ensure that the `/home/user/logs` directory exists before running.

**Comment by fabioz** [comment] 2019-09-16 11:07
@karthiknadig I think this is expected in the main branch (and should be fixed in the refactor branch). 

There are many assumptions regarding threads that aren't true with `gevent` and I don't think the code in `master` deals properly with that (so, I think we should revisit this when the refactor branch stabilizes).

**Comment by picklit** [comment] 2019-09-16 19:23
@karthiknadig I made the config changes you requested, and have attached the log files here from my debug attempt here.  

I started the debugger session, the 1st breakpoint on the 'import locust' worked.  When I clicked continue, it again 'hung' I ended the debugging session.

[debug_logs.zip](https://github.com/microsoft/ptvsd/files/3617838/debug_logs.zip)

**Comment by jen6** [comment] 2019-10-13 10:48
I had same problem while using debugger.
The problem was monkey.patch_all should be called in the first running python file.
 to reproduce the problem make the project like this.
```
├── app
│   ├── __init__.py
│   └── __pycache__
│       └── __init__.cpython-37.pyc
└── test.py
```

`test.py`
```
# if import monkey at the first time debugger working well
#from gevent import monkey
#monkey.patch_all()

from app import func

if __name__ == '__main__':
    func()
    print('work')
```

`app.__init__.py`
```
# monkey patch in 
from gevent import monkey
monkey.patch_all()

import urllib3

def func():
    http = urllib3.PoolManager()
    r = http.request('GET', 'http://httpbin.org/robots.txt')
    print(r.status)
```

`launch.json`
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "stopOnEntry": true,
            "justMyCode": false,
            "console": "internalConsole",
            "gevent": true,
        }
    ]
}
```

I think it can be fixed. The pycharm use pydevd but it's debugger works well in the same code.
I'm trying to find out the problem in the source code.

**Comment by fabioz** [comment] 2020-01-07 12:13
I just checked here and in the master branch things are working properly (so, in ptvsd 5.x it's working).

**Closed by fabioz** 2020-01-07 12:13 UTC
Labels: Bug, area:Breakpoint, area:Settings
