### ISSUE TITLE
Exception triggered when trying to render an infinite generator

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#409] opened 2018-05-04 00:48 UTC
```python
import itertools
mycycle = itertools.cycle((1,2,3))
print('done!')
```

If you examine the attributes of `mycycle`, you get the following traceback:
```
Exception ignored in: <generator object using_format at 0x000001D0DBD4D2B0>
Traceback (most recent call last):
  File "C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x000001D0DBD4D5C8>
Traceback (most recent call last):
  File "C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
Exception ignored in: <generator object using_format at 0x000001D0DBD4D570>
Traceback (most recent call last):
  File "C:\Users\brcan\Desktop\some bunk\.venv\lib\site-packages\ptvsd\wrapper.py", line 859, in using_format
    yield futures.Result(context())
SystemError: error return without exception set
```

**Comment by brettcannon** [comment] 2018-05-04 00:49
Found by Microsoft/vscode-python#1370

**Comment by int19h** [comment] 2018-05-04 01:06
Looks like yet another dupe of #397.

**Comment by brettcannon** [comment] 2018-05-04 22:10
If it's a dupe then feel free to close.

**Comment by MikhailArkhipov** [comment] 2018-05-17 16:42
Please reopen if you still see it.

**Closed by MikhailArkhipov** 2018-05-17 16:42 UTC
Labels: bug
