### ISSUE TITLE
Multi-processing issue in VS code debugger

### ISSUE THREAD

**Issue by gauravmunjal13** [microsoft/ptvsd#2129] opened 2020-06-20 08:11 UTC
## Environment data

- PTVSD version: 1.46.1
- OS and version: Darwin x64 19.4.0
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.5.3  64-bit
- Using VS Code or Visual Studio: VS code

## Actual behavior

On using VS code for debugging PyTorch code on enumerator(data_loader) line, there is the following error: 

```
RuntimeError: already started
E00019.065: Exception escaped from start_client
...
AssertionError: can only join a child process
```

## Expected  behavior

The error happening because of doing multi-processing in data-loader. This has happened specifically when I updated the VS code to 1.46.1 yesterday. 

The expected behavior is not to give any error on enumerating the data loader in PyTorch, which was the case before updating VS code.

## Steps to reproduce:
1. Update the VS code to 1.46.1
2. Run the VS code debugger for enumerating the data loader in PyTorch

However, if I set num_workers=0 or use the following code before enumerating data loader resolves the issue:
```
import multiprocessing
multiprocessing.set_start_method('spawn', True)
```

Is there another way to resolve this? Or I am missing any configuration settings?

Thank you!

Kind regards,
Gaurav Kumar

**Comment by gauravmunjal13** [comment] 2020-06-20 11:55
I would like to add another strange behaviour with the debugger on using the following code before iterating over the data loader in PyTorch:
```
import multiprocessing
multiprocessing.set_start_method('spawn', True)
```
When the execution comes across enumerate(data_loader), it doesn't step into the __get_item__() method of the data loader even if I have set-up the breakpoints.

However, this wasn't observed on rather using num workers = 0.

**Comment by noymer** [comment] 2020-06-22 02:47
>PTVSD version: 1.46.1

Isn't it PTVSD version: 4.3.2?
I updated vscode to 1.46.1, then had the same error.

**Comment by noymer** [comment] 2020-06-22 02:54
There seems to be the same error in vscode-python repo.
https://github.com/microsoft/vscode-python/issues/12481
https://github.com/microsoft/vscode-python/issues/12476

**Comment by int19h** [comment] 2020-06-22 03:14
You're still running ptvsd 4. This is possible even with the most recent vscode-python version, if you have explicitly opted out from the new debugger experiment. Can you please check your settings, and make sure that you *DON'T* have any of this:
```json5
    "python.experiments.optOutFrom": [
        "DebugAdapterFactory - experiment",
        "PtvsdWheels37 - experiment"
    ],
```
(conversely, you can use "python.experiments.optIn" to force it - but you shouldn't need to, if you haven't opted out)

**Comment by int19h** [comment] 2020-06-22 04:21
Duplicate of https://github.com/microsoft/vscode-python/issues/12481 - please see the comments there for a workaround.

**Closed by int19h** 2020-06-22 04:21 UTC
