### ISSUE TITLE
Print does not work in VS Code debugger

### ISSUE THREAD

**Issue by lejongsuk** [Microsoft/ptvsd#1158] opened 2019-02-20 19:30 UTC
## Environment data

- PTVSD version: ptvsd 4.2.4
- OS and version: Win 8.1
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.1 Anaconda 
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Throws error:
Exception has occurred: AttributeError
'NoneType' object has no attribute 'write'
  File "D:\VSCode\test.py", line 1, in <module>
    print('hello world')

## Expected  behavior

Should print hello world

## Steps to reproduce:
1. run 
`  print('hello world') `
  in debug mode in VS Code

**Comment by karthiknadig** [comment] 2019-02-20 20:28
@lejongsuk Does this also happen with just python 3.7, not anaconda?

**Comment by lejongsuk** [comment] 2019-02-20 22:32
@karthiknadig I am not sure what you are asking. Program runs fine on jupyter, or via command python filename.py. However when i try to run in debug mode in VS code, the aforementioned error pops. Seems like a debugger issue not a python issue.

**Comment by karthiknadig** [comment] 2019-02-20 22:46
I am not able to repro in this on my end. So I was wondering if this is specific to the environment. Can you check if this is using ptvsd==4.2.4? You may have ptvsd installed in your environment but VSC launches a version that is shipped with it, unless us specifically set it to launch a custom debugger.

**Comment by lejongsuk** [comment] 2019-02-21 04:01
Umm I do have ptvsd of 4.2.4, I installed vs code only last week. Could you tell me how to launch with a custom debugger?

**Comment by karthiknadig** [comment] 2019-02-21 04:37
If you installed recently then it should be 4.2.3 (VS Code ships with 4.2.3). Can you do the following and share the log file. Be sure to remove any personal info from the log. 

Add `"logToFile": true`, in launch config, and repro the issue. The log file should be created in `%USERPROFILE%\.vscode\extensions\ms-python.python-2019.1.0` with the name `debug*.log`.

Running custom debugger should not be necessary. It is useful while working on the debugger itself.

**Comment by lejongsuk** [comment] 2019-02-21 06:45
[debug6152.log](https://github.com/Microsoft/ptvsd/files/2888003/debug6152.log)
Attached the log

**Comment by karthiknadig** [comment] 2019-02-21 07:57
In your settings.json, Can you change the following property:
`"python.pythonPath": "D:\\Aanaconda\\python.exe"`

From the logs it looks like it is using `pythonw.exe`, it should be set to `python.exe`

**Comment by fabioz** [comment] 2019-02-21 16:33
Closing as this is actually a duplicate of https://github.com/Microsoft/ptvsd/issues/1023 (the workaround as @karthiknadig said is using `python.exe` instead of `pythonw.exe`).

**Closed by fabioz** 2019-02-21 16:33 UTC
Labels: Investigate

**Comment by lejongsuk** [comment] 2019-02-22 00:03
Thanks a lot, it works now! :) :+1:
