### ISSUE TITLE
ptvsd -m ... doesn't work for modules in current directory

### ISSUE THREAD

**Issue by int19h** [Microsoft/ptvsd#1010] opened 2018-11-12 20:44 UTC
Suppose we're in a folder that contains a file named `foo.py`. This works:
```
python -m foo
```
but this doesn't:
```
python -m ptvsd -m foo
```
It can be made to work if the folder is manually added to `PYTHONPATH`, but this shouldn't be necessary - the behavior of `ptvsd -m` should correspond exactly to the behavior of `python -m`.

**Comment by int19h** [comment] 2018-11-12 20:46
This appears to be a pydevd limitation - ptvsd simply rewrites the arguments for pydevd, but this can be observed with pydevd alone. For example, this also doesn't work:
```
pydevd --port 5678 --client localhost --module --file foo:
```
@fabioz, can you clarify if this is by design?

**Comment by int19h** [comment] 2018-11-12 20:50
Of note, this does work:
```
python3 -c "import runpy; runpy.run_module('foo')"
```
as does this:
```
py -3 -c "import runpy; runpy._run_module_as_main('foo', alter_argv=False)"
```

**Comment by hernandp** [comment] 2018-11-13 22:41
I found also this behavior but I think this was working in previous releases.  Did the new version introduce a bug ?  Now I need to add directory to PYTHONPATH to launch modules for debugging. Thanks.

**Comment by MaxPowerWasTaken** [comment] 2018-11-16 15:20
The package developer of VSCode's Python extension says the workaround proposed here (adding project folder to pythonpath) was the cause of another issue I encountered trying to use the VSCode/Python debugger: https://github.com/DonJayamanne/pythonVSCode/issues/1441

**Comment by mattyfresh** [comment] 2018-11-27 22:07
@MaxPowerWasTaken Is there a copy of that issue in https://github.com/Microsoft/vscode-python?  Getting a 404, looks like everything has been moved to that new repo.  Just got the debugger working for python modules by adding my project to the `PYTHONPATH`, but if it's just going to cause more issues down the road would like to weigh my options.  Thanks!

**Comment by fabioz** [comment] 2018-11-29 16:40
I wasn't able to reproduce it with the latest master (the only thing is that `ptvsd` required me to pass the `--host` and `--port` to run)... 

See shell output below:

```
(ptvsd) ~/Desktop/ptvsd_workspace$ echo "print('on module')" > foo.py
(ptvsd) ~/Desktop/ptvsd_workspace$ python --version
Python 3.6.5 :: Anaconda, Inc.
(ptvsd) ~/Desktop/ptvsd_workspace$ python -m foo
on module
(ptvsd) ~/Desktop/ptvsd_workspace$ python -m ptvsd -m foo
usage: python -m ptvsd [-h] [--nodebug] [--client] --host HOST --port PORT
                       [--multiprocess] [-m MODULE] [-c CODE] [--pid PID]
                       [--single-session] [--wait] [-V]
                       [filename]
python -m ptvsd: error: the following arguments are required: --host, --port
(ptvsd) ~/Desktop/ptvsd_workspace$ python -m ptvsd --host 127.0.0.1 --port 3456 -m foo
on module
(ptvsd) ~/Desktop/ptvsd_workspace$ source deactivate
~/Desktop/ptvsd_workspace$ source activate py27
(py27) ~/Desktop/ptvsd_workspace$ python --version
Python 2.7.15 :: Anaconda, Inc.
(py27) ~/Desktop/ptvsd_workspace$ python -m foo
on module
(py27) ~/Desktop/ptvsd_workspace$ python -m ptvsd --host 127.0.0.1 --port 3456 -m foo
on module
(py27) ~/Desktop/ptvsd_workspace$ 
```

So, it seems to work testing with Python 2.7 and 3.6 (on Linux) for me... are you doing something different or is this actually fixed on master? 

-- as a note, my `PYTHONPATH` is not including the current directory, I only included `ptvsd/src` for it to find `ptvsd`.

**Comment by MaxPowerWasTaken** [comment] 2018-11-29 16:46
@mattyfresh yeah my other issue seems to have been deleted after it was closed with the suggestion not to include my project repo in the pythonpath, don't think the issue was moved to the Microsoft fork. But hey man if it's working for you I wouldn't sweat it.

**Comment by dennispg** [comment] 2018-12-05 16:11
I am having the same issue, and this did definitely work in a prior version.

I am able to work around for now by adding `"env": { "PYTHONPATH": "${workspaceRoot}"}` to launch.json configuration.

I am on version 2018.11.0 of the `ms-python.python` extension, and 1.29.1 of vscode.

Is this the wrong place to post this issue and should it be posted elsewhere?

**Comment by fabioz** [comment] 2018-12-06 19:12
Note: although `python -m ptvsd --host 127.0.0.1 --port 3456 -m foo` does work for me, a launch such as the one below didn't work (will investigate).

```
{
    "name": "Python: foo module",
    "type": "python",
    "request": "launch",
    "module": "foo",
    "console": "integratedTerminal",
}
```

**Comment by fabioz** [comment] 2018-12-08 19:18
Ok, just provided pull request to fix this (https://github.com/Microsoft/ptvsd/pull/1069). It worked when launching with `python -m ptvsd` because python itself added `''` to the `PYTHONPATH` in that case (which made it find the module), but when launching regularly from `ptvsd` the launcher was invoked with the full path (thus `''` was not added to the `PYTHONPATH` and the module was not found).

**Closed** 2018-12-10 18:17 UTC
Labels: bug, priority:P1, upstream-pydevd
