### ISSUE TITLE
Variable check

### ISSUE THREAD

**Issue by hugomartins11** [microsoft/ptvsd#1620] opened 2019-07-24 18:13 UTC
It'd be nice to check the value of some local vars, without having to use the cursor on top of them. 
I recommend putting it on a tab of the debugger interface and having it being displayed there.

**Comment by int19h** [comment] 2019-07-24 18:41
You can see all the local variables and their values in the Debug sidebar.

https://code.visualstudio.com/docs/editor/debugging#_debug-view
https://code.visualstudio.com/docs/editor/debugging#_data-inspection

Or did you have something else in mind?

**Comment by hugomartins11** [comment] 2019-07-24 20:43
Hello!
I did have something else in mind.
Having the ability to check global vars, for example, would be a plus.
This feature is present on pycharm for example

**Comment by int19h** [comment] 2019-07-24 20:47
Indeed! We have globals on our list of features to implement - #118. Please upvote that issue, so that we can keep track of the user demand for it, and prioritize it accordingly.

**Comment by karthiknadig** [comment] 2019-07-24 20:57
Closing this as dupe of  #118

**Closed** 2019-07-25 05:18 UTC
