### ISSUE TITLE
Debugger continues to debug after program end

### ISSUE THREAD

**Issue by RaymonGulati1** [microsoft/ptvsd#1553] opened 2019-07-02 00:41 UTC
## Environment data

- PTVSD version: 4.2.10
- OS and version: Windows 10, 1809
- Python version: CPython
- Using VS Code or Visual Studio: VS

## Actual behavior
PTVSD stays in debug mode after a process has finished executing.

## Expected  behavior
After a process has finished executing, VS should stop debugging. 

## Steps to reproduce:
1. Write a python test suite and start debugging it
2. Wait until all the tests have finished debugging
3. Eventually the python process running the tests will end and the test results will be displayed, however, VS will stay in debug mode. 

![image](https://user-images.githubusercontent.com/3315992/60474505-35190300-9c27-11e9-82db-99085af2ea9a.png)

**Comment by karthiknadig** [comment] 2019-07-02 00:55
Can you provide the debug adapter logs as well?

**Comment by RaymonGulati1** [comment] 2019-07-02 22:54
Attached 
[DebugAdapterHost.txt](https://github.com/microsoft/ptvsd/files/3352590/DebugAdapterHost.txt)

**Comment by int19h** [comment] 2019-07-02 23:27
One possibility is that the Python process has background threads that were not set to `daemon=True`. Python does not exit until all such threads exit. 

If so, these threads - and their stacks - should be visible if you hit Pause.

**Comment by karthiknadig** [comment] 2019-07-03 03:24
@Raymongulati1 How are you starting the test process? Are you using `ptvsd` CLI or using `enable_attach`.

**Comment by int19h** [comment] 2019-07-03 03:43
Also, we just discussed this, and it's possible that some threads might not show up in the Threads list, but still block the process...

There's something in ptvsd to debug this type of issues, though:

https://github.com/microsoft/ptvsd/blob/82b62b77b5896429bd7e72de11cb7adcdc0ad54c/src/ptvsd/common/stacks.py#L19-L21

https://github.com/microsoft/ptvsd/blob/82b62b77b5896429bd7e72de11cb7adcdc0ad54c/src/ptvsd/common/stacks.py#L53-L55

The idea is that when you get a hang like this, you can call `dump_after(10)` as the very last thing you do in that process, and then see what's still running in 10 seconds.

This code is in the branch where we are doing refactoring, so it won't be in your copy of ptvsd - you can't invoke it directly (yet). But it has minimal dependencies - the only part it uses from other ptvsd modules is `log.info()` and `log.exception()`. So you should be able to copy/paste that code, and replace `log(...)` with `print(format(...))`; everything else should work exactly as is.

**Comment by RaymonGulati1** [comment] 2019-07-05 21:45
@int19h 
I pressed pause and I got an error message. 
![image](https://user-images.githubusercontent.com/3315992/60746343-225a4300-9f33-11e9-8847-eab699bbc2f8.png)

I went through the process of getting the thread information. I had to set the dumper tread as dameon = false orelse it wouldn't generate an output. I'll send you the logs in private chat. 


@karthiknadig
I started the process with "Run selected tests" and then attached the debugger using enable_attach. The new debugger for python unit tests has not been intergrated in PTVS/master, so you will need to use [my branch](https://github.com/RaymonGulati1/PTVS/tree/issue-3907-updated-debugger-for-test-explorer) if you want to reproduce the results exactly like mine.

**Comment by fabioz** [comment] 2019-07-08 19:22
@RaymonGulati1 

Can you add the code below and provide the output after the run finishes and threads are dumped? 

-- It can be added to the start of the module as it'll create a thread to print a thread dump after the timeout elapses, you just need to set the proper `TIMEOUT` to make sure it triggers after the code finishes running.

```
import time
import traceback
import threading
import sys

TIMEOUT = 10

class DumpThreads(threading.Thread):
    def run(self):
        time.sleep(TIMEOUT)

        thread_id_to_name = {}
        try:
            for t in threading.enumerate():
                thread_id_to_name[t.ident] = '%s  (daemon: %s)' % (t.name, t.daemon)
        except:
            pass

        stack_trace = [
            '===============================================================================',
            'Threads still found running after tests finished',
            '================================= Thread Dump =================================']

        for thread_id, stack in sys._current_frames().items():
            stack_trace.append('\n-------------------------------------------------------------------------------')
            stack_trace.append(" Thread %s" % thread_id_to_name.get(thread_id, thread_id))
            stack_trace.append('')

            if 'self' in stack.f_locals:
                sys.stderr.write(str(stack.f_locals['self']) + '\n')

            for filename, lineno, name, line in traceback.extract_stack(stack):
                stack_trace.append(' File "%s", line %d, in %s' % (filename, lineno, name))
                if line:
                    stack_trace.append("   %s" % (line.strip()))
        stack_trace.append('\n=============================== END Thread Dump ===============================')
        sys.stderr.write('\n'.join(stack_trace))


dump_current_frames_thread = DumpThreads()
dump_current_frames_thread.setDaemon(True)  # Daemon so that this thread doesn't halt it!
dump_current_frames_thread.start()
```

**Comment by RaymonGulati1** [comment] 2019-07-09 18:24
@fabioz 

The python process finishes within the 10 seconds, so the daemon thread will never execute.

**Comment by fabioz** [comment] 2019-07-12 19:43
Closing as a duplicate of https://github.com/microsoft/ptvsd/issues/1571 (which has more information).

**Closed by fabioz** 2019-07-12 19:43 UTC
Labels: Bug
