### ISSUE TITLE
Print statement doesnt print onto debug console

### ISSUE THREAD

**Issue by Biarys** [microsoft/ptvsd#2048] opened 2020-01-19 04:57 UTC
## Environment data

- VS Code version: 1.38.1
- Extension version (available under the Extensions sidebar): 2020.1.58038 and 2020.1.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda, python 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: python in general
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): No

## Expected behaviour

Print statement prints in debug console. Autocomplete works/shows possible names of the variables.

## Actual behaviour

Print statement returns None without printing anything in the debug console, but the output shows in terminal since version 2020.1.0. Starting version 2020.1.58038, autocomplete doesnt work when printing in debug console.

## Steps to reproduce:
[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. try any print statement in debug mode
2. In version 2020.1.58038, try typing any variable name when debugging

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Nothing in the output
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
XXX
```

**Comment by int19h** [comment] 2020-01-20 09:53
Dupe of #2036

**Closed by int19h** 2020-01-20 09:53 UTC
