### ISSUE TITLE
Why does vs code debug console break python print statements after visual studio code upgrade to v1.33?

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1324] opened 2019-04-08 18:06 UTC
@alpmar commented on [Mon Apr 08 2019](https://github.com/Microsoft/vscode-python/issues/5154)

- VS Code version: 1.33.0 (just upgraded, issue was not present before upgrade)
- Extension version (available under the Extensions sidebar): Name: Python
Id: ms-python.python
Description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
Version: 2019.3.6352
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python
- OS and version: Yosemite, 10.10.5
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.5 Anaconda
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 

## Expected behaviour

1 2

## Actual behaviour at Debug Console

1

2

## Steps to reproduce:
a=1
b=2
print (a,b)

**Comment by int19h** [comment] 2019-04-08 18:40
Can't repro this on either Mac or Windows. @DonJayamanne, does it repro for you?

**Comment by fabioz** [comment] 2019-04-08 19:14
@int19h I can actually reproduce it here (only happens at the debug console, not when running the code).

![vscode_debug_print](https://user-images.githubusercontent.com/117621/55750143-0ec53c00-5a19-11e9-9742-20d84b0b367b.png)

**Comment by int19h** [comment] 2019-04-08 20:22
You're right, I was looking at the wrong window. 

Looking at ptvsd logs, it does return the correct sequence of output messages to VSC:
```
D00000.219: (while handling ('CMD_WRITE_TO_CONSOLE', 16))
            IDE <-- {
                "type": "event",
                "seq": 13,
                "event": "output",
                "body": {
                    "output": "1",
                    "category": "stdout",
                    "source": {}
                }
            }

D00000.219: (while handling ('CMD_WRITE_TO_CONSOLE', 18))
            IDE <-- {
                "type": "event",
                "seq": 14,
                "event": "output",
                "body": {
                    "output": " ",
                    "category": "stdout",
                    "source": {}
                }
            }

D00000.235: (while handling ('CMD_WRITE_TO_CONSOLE', 20))
            IDE <-- {
                "type": "event",
                "seq": 15,
                "event": "output",
                "body": {
                    "output": "2",
                    "category": "stdout",
                    "source": {}
                }
            }

D00000.235: (while handling ('CMD_WRITE_TO_CONSOLE', 22))
            IDE <-- {
                "type": "event",
                "seq": 16,
                "event": "output",
                "body": {
                    "output": "\n",
                    "category": "stdout",
                    "source": {}
                }
            }
```

Note that there's only one `\n` here. The newline between 1 and 2 in the window is introduced in VSC. So I think this might be a regression in the original bug that is referenced from this one: https://github.com/Microsoft/vscode/issues/17526

**Comment by fabioz** [comment] 2019-04-09 17:45
As a note, it seems that this was reported to vscode and closed there as `caused-by-extension` (https://github.com/Microsoft/vscode/issues/71964).

**Comment by int19h** [comment] 2019-04-09 19:00
@DonJayamanne, is there any logic on the extension side that connects `output` events to the debug console? Based on the log above, the problem reproduces even though the debugger is not sending any newlines other than the final one, so I'm curious what the referenced bug might be talking about.

**Comment by DonJayamanne** [comment] 2019-04-18 04:05
Sorry didn't see this.
> is there any logic on the extension side that connects output events to the debug console?

No.

>  so I'm curious what the referenced bug might be talking about.

Possible there's a regression in VS Code.
If it works at our end (PTVSD is doing the right thing and we can repro this), I'd say it's a regression in VSC and just file an issue upstream.

Please note, when filing an issue on VSC:
* Please mention the fact that it is NOT an extension issue
* Please provide logs

> As a note, it seems that this was reported to vscode and closed there as caused-by-extension (Microsoft/vscode#71964).

Again, if we're doing the right thing, please ping the team to re-open the issue and provide the logs. They'll open it once we've done our bit.

**Comment by karthiknadig** [comment] 2019-04-29 18:38
This is fixed in insiders version of VSCode:
![image](https://user-images.githubusercontent.com/3840081/56918610-50bf2c00-6a73-11e9-9a32-1713f7c4ce5b.png)

**Closed by karthiknadig** 2019-04-29 18:38 UTC

**Comment by chip-edw** [comment] 2019-05-04 10:55
why would you close this when you are still providing a broken download with no instructions to correct?

**Comment by karthiknadig** [comment] 2019-05-04 17:16
@chip-edw It is fixed in insiders build of vscode. This is was not a bug in `ptvsd`. You can download that here. https://code.visualstudio.com/insiders/

**Comment by int19h** [comment] 2019-05-04 23:39
In general, we follow the standard GitHub issue flow, whereby bugs are marked as resolved and closed once the commit that fixes them is in the master branch of the main repository. In most cases, this is [done automatically by GitHub itself](https://help.github.com/en/articles/closing-issues-using-keywords) based on commit messages in pull requests. For issues reported here that are fixed by commits in other repositories, we do the same manually once we verify the fix.

**Comment by chip-edw** [comment] 2019-05-05 11:30
Thank you. That helps
