### ISSUE TITLE
Django extremely slow on Windows

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1473] opened 2019-05-29 17:34 UTC
@jkw commented on [Wed May 29 2019](https://github.com/microsoft/vscode-python/issues/5831)

## Environment data

- VS Code version: 1.35.0-insiders
- Extension version (available under the Extensions sidebar): v2019.5.17059
- OS and version: Windows 10 Home Insider Build 18898.rs_prerelease.190510-1634
- Python version (& distribution if applicable, e.g. Anaconda): Official
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: Django v2.2.1

## Expected behaviour

A few ms loading time, not 5 min.

## Actual behaviour

5 min load time in Firefox, 40min+ Chrome.

## Steps to reproduce:
1. F5 to start debugger, choose django in venv.
2. Default start string is:
```
cd /home/jkw/dev ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /home/jkw/dev/hydra/py373/bin/python /home/jkw/.vscode-remote/extensions/ms-python.python-2019.5.17059/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 62933 /home/jkw/dev/hydra/hydra/manage.py runserver --noreload --nothreading
```

To fix the issue, start manually by typing the following in project root:
```
./manage.py runserver
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Not applicable.
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
Not applicable.
```
Pictures:
![ffperformance](https://user-images.githubusercontent.com/388872/58577546-00401780-8247-11e9-8bd9-a6910cba2ad3.png)
![chromeperformance](https://user-images.githubusercontent.com/388872/58577555-03d39e80-8247-11e9-9bbf-5e58c3d9b641.png)

**Comment by jkw** [comment] 2019-05-29 17:36
Could be fixed with removing the `--nothreading` from **launch.json** as well.

**Comment by fabioz** [comment] 2019-05-29 17:48
I believe this is a dupe of https://github.com/microsoft/ptvsd/issues/1393 (see comment: https://github.com/microsoft/ptvsd/issues/1393#issuecomment-489259007).

Please reopen if you feel that's not the case.

**Closed by fabioz** 2019-05-29 17:48 UTC

**Comment by jkw** [comment] 2019-05-29 18:23
It's a dupe. Sorry for not finding that while searching.

Den ons 29 maj 2019 19:48Fabio Zadrozny <notifications@github.com> skrev:

**Comment by fabioz** [comment] 2019-05-29 18:32
No problems, it's not always easy to find duplicates ;)
