### ISSUE TITLE
Dict keys order is altered in debug sessions even with Python 3.7+

### ISSUE THREAD

**Issue by beeb** [microsoft/ptvsd#2051] opened 2020-01-22 10:21 UTC
It seems to be the same as https://github.com/microsoft/vscode-python/issues/3236

## Environment data

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): 2020.1.58038
- OS and version: Windows 10 + macOS Catalina
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): miniconda
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): jedi

## Expected behaviour

In a debug session with Python 3.7+, insertion order of the keys in a dictionary are respected

## Actual behaviour

In a debug session with Python 3.7+, the keys of a dictionary get re-ordered (what seems like alphabetically).
It's important to note that executing the same code in an external terminal with the same conda environment, or even in an interactive python session in the internal terminal, leads to the expected behavior. This issue is specific to the debug console!

## Steps to reproduce:

1. Add a breakpoint in some python 3 source
1. Start a debugging session using a python 3.7+ environment
2. When the script pauses at the breakpoint, open the debug console
3. Initialize and populate a python `dict`, making sure the keys are not in alphabetical order
4. Type the name of the dict to display its value
5. Observe that the keys order is not anymore the insertion order, rather they are sorted alphabetically

![Capture](https://user-images.githubusercontent.com/703631/72885444-36fffc00-3d08-11ea-8d7e-097b4ade7bf5.PNG)

## Logs

Irrelevant I think?

**Comment by karthiknadig** [comment] 2020-01-22 20:33
This is a dupe of #998

**Closed by karthiknadig** 2020-01-22 20:33 UTC

**Comment by beeb** [comment] 2020-01-23 06:15
Wow, since the 9 november 2018? Any idea why this is taking so long?

**Comment by karthiknadig** [comment] 2020-01-23 07:50
@beeb it wasn't prioritized. Please up-vote the issue, since we take that into account while prioritizing.
