### ISSUE TITLE
PTVSD: Launcher / Debugger not working at all since last update.

### ISSUE THREAD

**Issue by Armitxes** [Microsoft/ptvsd#791] opened 2018-09-10 10:59 UTC
## Environment data

- PTVSD version: I really don't know. The latest one delivered with VS Code
- OS and version: Windows 10 - V1803 (Build 17134.228)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.5.1
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Today I've decided to update my VS Code Version and suddenly all my Python projects stopped working.
Before the update to PTVSD everything worked smoothly.

```cd 'P:\Software\Odoo\11.0\Workspace'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; ${env:PYTHONPATH}='c:\Users\Main\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd'; & 'P:\Software\Odoo\11.0\base\python-env-work\Scripts\python.exe' '-m' 'ptvsd' '--nodebug' '--host' 'localhost' '--port' '52370' 'P:\Software\Odoo\11.0\base\sources\community\odoo-bin' '-c' 'P:\Software\Odoo\11.0\Workspace\odoo11.cfg```

gives me the error:
```
File "c:\Users\Main\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "P:\Software\Odoo\11.0\base\sources\community\odoo-bin", line 5, in <module>
    import odoo
ImportError: No module named 'odoo'
```
Manually changing the launch parameter in the console to the following works:
```cd 'P:\Software\Odoo\11.0\Workspace'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; ${env:PYTHONPATH}='c:\Users\Main\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd'; & 'P:\Software\Odoo\11.0\base\python-env-work\Scripts\python.exe' 'P:\Software\Odoo\11.0\base\sources\community\odoo-bin' '-c' 'P:\Software\Odoo\11.0\Workspace\odoo11.cfg```

but I completly loose the debugging feature of VS Code by doing so and of course I wish to directly launch the python scripts without additional manual work.

## Expected  behavior

PTVSD shouldn't change the behaviour of how python is being executed. For some reason. with PTVSD python can't find the modules / files it can find without PTVSD.

Does VS Code atleast provide a way to return to the legacy debugger as Visual Studio does?

**Comment by karthiknadig** [comment] 2018-09-10 15:59
Can you provide some sample code to repro this? is this specific to `odoo`?

/cc @DonJayamanne

**Comment by Armitxes** [comment] 2018-09-11 11:11
It's specific to odoo.

Basically I only execute the [odoo-bin](https://github.com/odoo/odoo/blob/11.0/odoo-bin) via python which has an normal python import at line 5.

`import odoo` the target of the import is located in the same folder (`./odoo/__init__.py`) I don't see how it can't be found with ptvsd.


Has something changed for the launch.json? Just in case, here is mine:
```
{
    "configurations": [
        {
            "envFile": "${workspaceRoot}/.env",
            "cwd": "${workspaceRoot}",
            "env": {},
            "args": [
                "-c",
                "P:\\Software\\Odoo\\11.0\\Workspace\\odoo11.cfg"
            ],
            "name": "[v11] Default",
            "console": "integratedTerminal",
            "program": "P:\\Software\\Odoo\\11.0\\base\\sources\\community\\odoo-bin",
            "stopOnEntry": false,
            "pythonPath": "P:\\Software\\Odoo\\11.0\\base\\python-env-work\\Scripts\\python.exe",
            "request": "launch",
            "type": "python"
        }
    ],
    "version": "0.2.0"
}
```

**Comment by fabioz** [comment] 2018-09-11 16:40
This is actually strange... in https://github.com/Microsoft/ptvsd/blob/master/ptvsd/_vendored/pydevd/pydevd.py#L1058 the PYTHONPATH should be fixed to add that directory.

Now, this was a recently recent fix (done in https://github.com/fabioz/ptvsd/commit/e63e0f2add0f152d7d0fbdbdc004c4752df60284 to fix https://github.com/Microsoft/ptvsd/issues/745), so, maybe it's still not released...

@karthiknadig do you know if that fix is already in the latest release?

**Comment by karthiknadig** [comment] 2018-09-11 17:35
@fabioz The fix for the issue is in master but not in the release.

**Closed** 2018-09-14 21:49 UTC
