### ISSUE TITLE
ptvsd_launcher.py prevents jira from importing in buildout environment

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1229] opened 2019-03-11 17:42 UTC
@Cetlan commented on [Sat Mar 09 2019](https://github.com/Microsoft/vscode-python/issues/4700)

## Environment data

- VS Code version: 1.31.1
- Extension version (available under the Extensions sidebar): 2019.2.5558
- OS and version: Windows 10 and Mac OS X Maverick
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.15 / 2.7.16
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): buildout (with and without virtualenv wrapping the buildout tools) 
- Relevant/affected Python packages and their versions: jira 

## Expected behaviour

jira module imports

## Actual behaviour

jira module does not import

## Steps to reproduce:
install zc.buildout (using pip)
run `buildout` with the following configuration:

buildout.cfg
```
[buildout]
parts = py

[py]
eggs = jira
recipe = zc.recipe.egg
interpreter = python
```

Create a script (`importbug.py`) that just imports jira.

We need to get a little creative in the launch.json now, because buildout creates a script that provides paths, and while "typical" use would be to just run the script `bin/python`, we can't select that as the interpreter. So use the following launch configuration

```
        {
            "name": "Jira Loader",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/bin/python",
            "args": ["${workspaceFolder}/importbug.py"],
            "console": "integratedTerminal",
        }
```

If you're trying this on Windows, 'bin/python' is a binary, so you'll need to replace `bin/python` in the launch configuration with the matching script `bin/python-script.py`. Trying to run this through vscode, generates an error that jira couldn't be loaded (or couldn't be found, depending on the system/versions of things). Running it using the same command line that vscode uses also causes the same error. Running with that same command line, but removing the `ptvsd_launcher.py` from the command makes the script run perfectly.
## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```

```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
Traceback (most recent call last):
  File "c:\Users\clansing\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\clansing\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\__main__.py", line 357, in main
    run()
  File "c:\Users\clansing\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\__main__.py", line 257, in run_file
    runpy.run_path(target, run_name='__main__')
  File "c:\users\clansing\applications\python27\Lib\runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "c:\users\clansing\applications\python27\Lib\runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "c:\users\clansing\applications\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\clansing\Projects\vscodepkgs/bin/python-script.py", line 49, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "C:\Users\clansing\Projects\vscodepkgs/src/jiraloader.py", line 2, in <module>
    import jira
  File "c:\users\clansing\projects\vscodepkgs\eggs\jira-2.0.0-py2.7.egg\jira\__init__.py", line 6, in <module>
    _v = VersionInfo('jira').semantic_version()
  File "c:\users\clansing\projects\vscodepkgs\eggs\pbr-5.1.3-py2.7.egg\pbr\version.py", line 462, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "c:\users\clansing\projects\vscodepkgs\eggs\pbr-5.1.3-py2.7.egg\pbr\version.py", line 449, in _get_version_from_pkg_resources
    result_string = packaging.get_version(self.package)
  File "c:\users\clansing\projects\vscodepkgs\eggs\pbr-5.1.3-py2.7.egg\pbr\packaging.py", line 849, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name jira was given, but was not able to be found.

```
Note: the above debug console output is slightly different on the OS X system I originally hit this problem on. The exception was less verbose, and basically just said it couldn't find jira - but I'm assuming it's the same problem, just slightly different versions of things.

**Comment by int19h** [comment] 2019-03-11 19:13
This doesn't look like an issue with Jira not being found - it's actually on the stack, but is failing for some reason.

**Comment by Cetlan** [comment] 2019-03-13 00:34
Some additional information and a seemingly usable workaround:

If the launcher has the buildout-generated `${workspace}/bin/python` script explicitly set as `pythonPath` with `program` set to the jira-loading script instead of using the buildout-generated `${workspaceFolder}/bin/python` script as the program with the jira-loading script as an argument to it, it seems to work - even if the selected python interpreter is the same one as `${workspaceFolder}/bin/python` was generated to use if run by itself.

I say "seemingly usable" because it works around the simple reproduce, but I'm still having some trouble with the larger case that first displayed this, and I'm unable so far to simplify it (so it may not be related).

**Comment by gramster** [comment] 2019-04-03 22:53
It sounds like this was just an issue with figuring out the right way to configure this, and there's nothing here for the debugger to do. @Cetlan, do you agree? If so please close this.

**Comment by Cetlan** [comment] 2019-04-04 14:07
I still feel like there's something strange going on, as I don't see a reason why the extra level of "indirection" should have caused a problem, and it's a little annoying to set up because the buildout python wrapper can't be selected as the interpreter, it has to be hand-edited in, and hope nobody accidentally overwrites it from the UI.

But it's functional and this is a pretty specific case. So I'm willing to say "meh, it works" unless it recurs in other situations.

**Closed** 2019-08-07 21:38 UTC
Labels: Bug, Needs-more-info
