### ISSUE TITLE
colored print no longer works in terminal

### ISSUE THREAD

**Issue by waclaw66** [microsoft/ptvsd#1960] opened 2019-11-29 08:57 UTC
## Environment data

- VS Code version: 1.40.2
- Extension version (available under the Extensions sidebar): 2019.11.50794
- OS and version: Win10 x64 1709
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3 or 3.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: colorama, colored
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Jedi

## Expected behaviour

Printed text should be colored according the code

## Actual behaviour

Printed text is in default terminal color (grey)

## Steps to reproduce:
[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install VSCode 1.40.2, Python 3.8, VSCode Python extension 2019.11.50794
2. Install colorama package (pip install colorama)
3. Run following code:

2019.11.50794
![obrazek](https://user-images.githubusercontent.com/15554561/69853357-f98e6d80-1286-11ea-808d-d91731dcb263.png)

2019.10.44104 (last working version)
![obrazek](https://user-images.githubusercontent.com/15554561/69856321-abc93380-128d-11ea-9c02-c56e07b1820a.png)

I tried to reinstall Python, colorama package, VSCode (tried also old versions), python extension. Cache flushed, but no luck.

**Comment by int19h** [comment] 2019-12-02 21:46
This is the consequence of "RedirectOutput" being implemented out-of-proc in ptvsd 5. The result is that `sys.stdout.isatty()` is false, and then Colorama disables colored output.

I don't think we can fix this with `"redirectOutput": true` being enabled, unless we revert to the old behavior of capturing output in-proc (which causes its own issues). That said, https://github.com/microsoft/ptvsd/pull/1956 changed the default for that setting to false if you're using integrated or external terminal, which fixes the issue. There's another problem in that vscode-python itself is overriding the new default - this is tracked by #8865.

**Comment by int19h** [comment] 2019-12-18 20:10
We've changed the default for "redirectOutput" in both ptvsd and vscode-python, so this should be fixed for regular debug configs. When "redirectOutput" is explicitly enabled, the behavior is considered by design for now.

**Closed by int19h** 2019-12-18 20:10 UTC
