### ISSUE TITLE
Error popup when debug flask

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/ptvsd#1928] opened 2019-11-19 08:08 UTC
Visual Studio Code - Insiders: 1.41.0-insider
python-insider: 2019.12.49019-dev
python version: Python 3.8.0 64bit
Install Anaconda

Repro steps:
1.Git clone https://github.com/qubitron/pydemo
2.Open Anaconda Prompt window
3.Cd pydemo
4.Run py -3 setup.py
5.Set "python.jediEnabled" to "false" in "Settings.json"
6. Open "Stackoverflow-flask" folder
7. Select "Debug“
8. Select "Add Configuration..." in "DEBUG" dropdown menu
9. Customize the path in launch.json:
![image](https://user-images.githubusercontent.com/41426540/69128052-7a5ea400-0ae6-11ea-98fe-7ad92aef6f72.png)
10. Set "DEBUG" to "Python:Flask"
11. Open "app->main.py" to debug

Actual Result:
Error popup "Session-1 timed out waiting for debuggee to spawn" when start to debug
![image](https://user-images.githubusercontent.com/41426540/69128171-bbef4f00-0ae6-11ea-863a-967d0a36cade.png)

Expect Result:
Debug successfully

**Comment by karthiknadig** [comment] 2019-11-19 09:52
@xiaofeng0123 Can you confirm this happens even if you use `"FLASK_APP": "app.main"`? FLASK_APP should be the name of the module, according to the docs:  https://flask.palletsprojects.com/en/1.1.x/quickstart/#invalid-import-name

@int19h From the screen shot it looks like the environment variable `FLASK_APP` is not getting set correctly. Should it be setting that before ` & ` ?

**Comment by int19h** [comment] 2019-11-19 17:22
This is using `"console":"internalConsole"` (default value) rather than `"integratedTerminal"`, so there's no command line corresponding to the debuggee in the terminal, and thus no environment variables - you only see the command line for the launcher, and the launcher gets the env vars from the "launch" request that's forwarded to it.

This is also likely why there's no error output from Flask in the terminal. Switching it to `"console":"integratedTerminal"` might provide better diagnostics.

**Comment by xiaofeng0123** [comment] 2019-11-20 02:53
I have tried this by setting `"FLASK_APP": "app/main.py"` and `"FLASK_APP": "app.main"` in new test environment. The error popup when debug at the first time, It works OK after the second time.

**Comment by int19h** [comment] 2020-01-21 21:04
@xiaofeng0123, can you please try this on the most recent version of VSCode and Python extension?

**Comment by int19h** [comment] 2020-05-04 19:58
Couldn't reproduce, likely to be fixed in the more recent versions.

**Closed by int19h** 2020-05-04 19:58 UTC
Labels: Bug
