### ISSUE TITLE
Matplotlib SIGSEV error

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1437] opened 2019-05-20 16:51 UTC
@narekmargaryan commented on [Sun May 19 2019](https://github.com/microsoft/vscode-python/issues/5689)

Running on Ubuntu 19.04.

All works fine when I launch the terminal (externally, not within the VS Code) and run the .py from there. As soon as I try to debug inside Code or even run the file from the embedded terminal, I receive

"fish: “env PYTHONIOENCODING=UTF-8 PYTH…” terminated by signal SIGSEGV (Address boundary error)"

on the line where I call 'plt' for the first time (i.e. plt.plot([1,2,3]) for example).

When I launch in the external terminal (again, from within Code), I receive:

bash: line 1:  6635 Segmentation fault      (core dumped) ''/usr/bin/python3 /home/user/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 44817 /home/user/Documents/Projects/test.py

**Comment by fabioz** [comment] 2019-05-20 17:03
@narekmargaryan can you provide some sample code where you're getting this error?

**Comment by narekmargaryan** [comment] 2019-05-20 17:09
@fabioz 

```
import matplotlib.pyplot as plt

plt.plot([1,2,3])
```

**Comment by fabioz** [comment] 2019-05-20 17:32
I can't reproduce this (checked in Ubuntu with Python 3.6). 

Can you provide more details on the Python version and matplotlib version where you're getting the error? Also, can you share your launch config?

**Comment by narekmargaryan** [comment] 2019-05-20 19:50
Sure,

python 3.7.3
matplotlib 3.1.0
code 1.34.0
Linux x64 5.0.0-15

**Comment by int19h** [comment] 2019-05-20 20:29
Try setting the environment variable `PYDEVD_USE_FRAME_EVAL` to `NO` in your launch.json config - does that change anything for you?

**Comment by narekmargaryan** [comment] 2019-05-20 20:40
Still receiving 

`PYDEVD_USE_FRAME_EVAL`

my launch.json looks like this:

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "env": {"PYDEVD_USE_FRAME_EVAL": "NO"}
        }
    ]
}`

**Comment by fabioz** [comment] 2019-05-27 17:29
Can you print your `environ` in and out of VSCode?

Please use the code below and run it from the shell and from VSCode and post the output (my guess is that you have some environment variable different -- such as `LD_LIBRARY_PATH` or `PATH` and that difference makes it crash).

```
import os
for key, val in os.environ.items():
    print('\n%s:' % (key,))
    for v in val.split(os.pathsep):
        print('    %s' % (v,))
```

Also, when you say that if fails if you: `run the file from the embedded terminal`, do you mean that if you don't use the launch and just write: `/usr/bin/python3 /home/user/Documents/Projects/test.py` in the VSCode terminal, it fails too?

**Comment by narekmargaryan** [comment] 2019-06-20 03:09
Hi @karthiknadig,

Sorry for the late reply.
For your second question, yes, still happening.

For the first one, the output is:

`
import os
for key, val in os.environ.items():
    print('\n%s:' % (key,))
    for v in val.split(os.pathsep):
        print('    %s' % (v,))
`

**Comment by gramster** [comment] 2019-09-03 23:58
We can't repro this; closing.

**Closed by gramster** 2019-09-03 23:58 UTC
Labels: Bug

**Comment by mbristol78** [comment] 2020-04-30 20:51
Has anyone found a solution for this? i am having the same problem.
A simple matplotlib like 
```
import matplotlib.pyplot as plt
print("Hello World")
plt.plot([1,2,3],[5,7,4])
plt.show()
print("bye world")
```
Using an external bash terminal with or without fish, all good. 
Using the vscode embedded terminal with or without fish, SIGSEGV at line plt.plot
Debugging or running the py file with the vscode embedded terminal, SIGSEGV.

 However, using the embedded vscode terminal with or without fish, if you type 
```
sudo python3 my_file.py
```
Then it works fine.
So this is a permission error,installation? 
I have change the time in  
```
sudo visudo
```
in the embedded vscode terminal, in order not to get to type ```sudo``` but it wont change the error at run time.
