### ISSUE TITLE
mxnet cause vscode debugger to throw exception

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/ptvsd#1650] opened 2019-08-01 04:13 UTC
I'm trying to step through an mxnet machine learning model in vscode. Whenver I get to the line

    train_data = gluon.data.DataLoader(train_datasets[dataset_index], shuffle=True, batch_size=options.batch_size,
                                       num_workers=8,
                                       batchify_fn=batchify)

vscode throws the exception below. I don't beleive this is thrown from the `gluon.data.DataLoader()` method as the code runs fine if I execute from the console so it appears to be a vscode launcher problem.

I'm not sure what else I can provide to make this easier to reproduce?

> E00001.423: Exception escaped from start_client
>             
>             Traceback (most recent call last):
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
>                 return f(*args, **kwargs)
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
>                 sock, start_session = daemon.start_client((host, port))
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
>                 with self.started():
>               File "/home/david/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 81, in __enter__
>                 return next(self.gen)
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
>                 self.start()
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
>                 raise RuntimeError('already started')
>             RuntimeError: already started
>             
> 
> Traceback (most recent call last):
> 
> Traceback (most recent call last):
>   File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 378, in __call__
>     py_db.notify_thread_not_alive(get_current_thread_id(t))
>   File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1108, in notify_thread_not_alive
>     was_notified = thread.additional_info.pydev_notify_kill
> AttributeError: 'NoneType' object has no attribute 'pydev_notify_kill'
> E00001.428: Exception escaped from start_client
>             
>             Traceback (most recent call last):
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
>                 return f(*args, **kwargs)
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
>                 sock, start_session = daemon.start_client((host, port))
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
>                 with self.started():
>               File "/home/david/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 81, in __enter__
>                 return next(self.gen)
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
>                 self.start()
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
>                 raise RuntimeError('already started')
>             RuntimeError: already started
>             
> 
> Traceback (most recent call last):
> 
> Traceback (most recent call last):
>   File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 378, in __call__
>     py_db.notify_thread_not_alive(get_current_thread_id(t))
>   File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1108, in notify_thread_not_alive
>     was_notified = thread.additional_info.pydev_notify_kill
> AttributeError: 'NoneType' object has no attribute 'pydev_notify_kill'
> E00001.430: Exception escaped from start_client
>             
>             Traceback (most recent call last):
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
>                 return f(*args, **kwargs)
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
>                 sock, start_session = daemon.start_client((host, port))
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
>                 with self.started():
>               File "/home/david/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 81, in __enter__
>                 return next(self.gen)
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
>                 self.start()
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
>                 raise RuntimeError('already started')
>             RuntimeError: already started
>             
> 
> Traceback (most recent call last):
> 
> Error in atexit._run_exitfuncs:
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 378, in __call__
>     py_db.notify_thread_not_alive(get_current_thread_id(t))
>   File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1108, in notify_thread_not_alive
>     was_notified = thread.additional_info.pydev_notify_kill
> 
> AttributeError: 'NoneType' object has no attribute 'pydev_notify_kill'
> Error in atexit._run_exitfuncs:
> E00001.434: Exception escaped from start_client
>             
>             Traceback (most recent call last):
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
>                 return f(*args, **kwargs)
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
>                 sock, start_session = daemon.start_client((host, port))
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
>                 with self.started():
>               File "/home/david/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 81, in __enter__
>                 return next(self.gen)
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
>                 self.start()
>               File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
>                 raise RuntimeError('already started')
>             RuntimeError: already started
>             
> 
> Traceback (most recent call last):
> Terminated
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
> 
> 
> Traceback (most recent call last):
>   File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 378, in __call__
>     py_db.notify_thread_not_alive(get_current_thread_id(t))
>   File "/home/david/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1108, in notify_thread_not_alive
>     was_notified = thread.additional_info.pydev_notify_kill
> AttributeError: 'NoneType' object has no attribute 'pydev_notify_kill'
> Error in atexit._run_exitfuncs:
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):

**Comment by int19h** [comment] 2019-08-01 17:53
It sounds similar to https://github.com/microsoft/ptvsd/issues/1056#issuecomment-457034475 - can you check the various workarounds in the comments there?

**Comment by david-waterworth** [comment] 2019-08-01 22:47
@int19h you're correct, it's the same issue. Adding

```
import multiprocessing
multiprocessing.set_start_method('spawn', True)
```

Disables forking a new process (#943).

**Comment by int19h** [comment] 2019-08-01 23:16
Thank you for confirming it! We'll use #943 to track the work needed to fix the root cause (which is ongoing - please bear with us!), so I'm going to close this one.

**Closed by int19h** 2019-08-01 23:16 UTC
Labels: Investigate
