### ISSUE TITLE
Issue with debug when using cmd as terminal

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1466] opened 2019-05-24 17:22 UTC
@petepall commented on [Thu May 23 2019](https://github.com/microsoft/vscode-python/issues/5742)

## Environment data

- VS Code version: 1.34.0
- Extension version (available under the Extensions sidebar): 2019.4.2
- OS and version: Windows 10 v1809
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.2 - 64bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...):  pipenv
- Relevant/affected Python packages and their versions: XXX

## Expected behaviour
When setting a breakpoint in a script and running the debug, the breakpoint should be hit and one can continue to debug from that point.

## Actual behaviour

When having a python script that contains the if __name__ = "__main__" function the debugger is not executing.

Running the debugger opens cmd.py and after a few moments an error message is showing saying "Timeout waiting for debugger connection"

![image](https://user-images.githubusercontent.com/42099752/58273299-af38ab00-7d90-11e9-96a0-028d4840bc7c.png)

## Steps to reproduce:
1. Make sure the Terminal is set to use the CMD.exe
2. build a simple script:
```Python
def print_name():
    print('hello name')


if __name__ == "__main__":
    print_name()
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
##########Linting Output - flake8##########
46,14,E,E401:multiple imports on one line
53,1,E,E302:expected 2 blank lines, found 1
151,5,E,E303:too many blank lines (2)
189,51,E,E701:multiple statements on one line (colon)
209,25,E,E203:whitespace before ':'
237,53,E,E228:missing whitespace around modulo operator
265,22,E,E225:missing whitespace around operator
301,24,E,E225:missing whitespace around operator
303,49,E,E228:missing whitespace around modulo operator
307,41,E,E228:missing whitespace around modulo operator
317,35,E,E225:missing whitespace around operator
326,24,E,E225:missing whitespace around operator
334,37,E,E228:missing whitespace around modulo operator
335,64,E,E231:missing whitespace after ','
336,67,E,E231:missing whitespace after ','
336,70,E,E231:missing whitespace after ','
337,64,E,E231:missing whitespace after ','
341,37,E,E228:missing whitespace around modulo operator
343,41,E,E228:missing whitespace around modulo operator
358,25,E,E127:continuation line over-indented for visual indent
364,37,E,E228:missing whitespace around modulo operator
402,37,E,E228:missing whitespace around modulo operator
##########Linting Output - mypy##########

```   

[Extension Host] Python Extension: Cached data exists getEnvironmentVariables, c:\Program Files\Python37\LIB\cmd.py

```
The terminal output is showing:

Treehouse_Course_files)  C:\Python programs\Treehouse_Course_files>
cd "c:\Python programs\Treehouse_Course_files" && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:\Users\PeterPallen\.virtualenvs\Treehouse_Course_files-TtKehXC6\Scripts\python.exe c:\Users\PeterPallen\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 50764 "c:\Python programs\Treehouse_Course_files\cmd_issue.py" "
```

---

@DonJayamanne commented on [Thu May 23 2019](https://github.com/microsoft/vscode-python/issues/5742#issuecomment-495372747)

> c:\Program Files\Python37\LIB\cmd.py

What's this and how is this related to the issue?
You have a screenshot and file opened in VSC, hence the question.

* Please could you create a new folder with just one file named `cmd_issue.py` and test this again. 
Let me know how that goes.

* Next, please could you try debugging an even simpler python file with the line `print("Hello")` in there (nothing else).

---

@petepall commented on [Thu May 23 2019](https://github.com/microsoft/vscode-python/issues/5742#issuecomment-495388146)

Hi Don,

The cmd.py, is not a script that I have in my script or that I'm calling.
When I start the debugger this cmd.py is getting called somehow.

I also checked, if I change the terminal from CMD to Powershell the debugging on this script is working without an issue. Somehow the debugger is calling this cmd.py file.

When there is no if __name__ = "__main__" entry in the script all is working as expected. The debugger starts and you can process the script, this works with this very simple script as well as a bigger script.

When you add the "if __name__ = "__main__"" into the file then the issue pop's it's head up.

If I put the cmd_issue.py into a separate folder with only these lines of codes, I get the issue again.
![image](https://user-images.githubusercontent.com/42099752/58287097-7c9eaa80-7db0-11e9-8616-162f6bf9d30c.png)

---

@petepall commented on [Thu May 23 2019](https://github.com/microsoft/vscode-python/issues/5742#issuecomment-495388438)

Here is the full screenshot of the vscode session.
![image](https://user-images.githubusercontent.com/42099752/58287286-f20a7b00-7db0-11e9-9ae9-a42fec5b0b0a.png)

---

@petepall commented on [Thu May 23 2019](https://github.com/microsoft/vscode-python/issues/5742#issuecomment-495392192)

The attached GIF shows the steps that I perform.

![CMD issue](https://user-images.githubusercontent.com/42099752/58287949-9d67ff80-7db2-11e9-9df9-b42e029c032d.gif)

**Comment by karthiknadig** [comment] 2019-05-24 17:30
@petepall Can you set `PTVSD_LOG_DIR` environment variable? to get the logs from the debugger. This can be done in the launch config in `launch.json`. for example:
```js
{
    "name": "Terminal",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "env": {
        "PTVSD_LOG_DIR": "C:\\logs",
    },
},
```

**Comment by petepall** [comment] 2019-05-24 19:56
@karthiknadig I added the `PTVSD_LOG_DIR` however no log is being created.

**Comment by DonJayamanne** [comment] 2019-05-24 20:00
@petepall Please could you take a screenshot instead of a video. Thanks for the video, however the resolution is not good enough, and difficult to read any text or make out whats going on.

It looks like the command for debugging isn't being sent to the terminal. Look at the video the terminal is at the prompt waiting for input.

**Comment by DonJayamanne** [comment] 2019-05-24 20:00
@karthiknadig It might be an issue with VSC, in which case you can close this issue.
Let wait for confirmation.

**Comment by petepall** [comment] 2019-05-24 20:08
@DonJayamanne Please find below the screenshot.
The text from the terminal is showing:

`C:\Python programs\issue>cd "c:\Python programs\issue" && cmd /C "set "PTVSD_LOG_DIR=C:\temp\logs" && set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && "C:\Program Files\Python37\python.exe" c:\Users\PeterPallen\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 62038 "c:\Python programs\issue\cmd_issue.py" "
`

![image](https://user-images.githubusercontent.com/42099752/58353967-488abe80-7e70-11e9-94ed-c09283a59b3b.png)

**Comment by karthiknadig** [comment] 2019-05-24 20:24
@petepall Ensure that the `C:\temp\logs` directory exists. If that logging is not working you can try, `"logToFile":true` in launch json. That should create VSC side logs for the debugger. These logs should be in the extension folder.

**Comment by petepall** [comment] 2019-05-24 21:58
@karthiknadig The folder exists and I have set the `"logToFile":true` into the launch.json file but still there is no log generated in the set folder.
I did find logs in the following folder `C:\Users\PeterPallen\AppData\Roaming\Code\logs`

These are the logs that are generated in that folder.
[Logs.zip](https://github.com/microsoft/ptvsd/files/3218719/Logs.zip)

**Comment by karthiknadig** [comment] 2019-05-24 22:02
Check this folder, the file should be named `debug<pid>.log`
`C:\Users\<user>\.vscode\extensions\ms-python.python-2019.4.12954`

**Comment by int19h** [comment] 2019-05-24 22:21
@karthiknadig, @DonJayamanne 
Note that the command line is using `cmd /c ...` to launch - i.e. the terminal is set up to use cmd rather than PowerShell.

And I think the way it is setting up those environment variables might be wrong. I just tried this:
```
C:\>cmd /C "set "PTVSD_LOG_DIR=C:\temp\logs" && echo %PTVSD_LOG_DIR%"
%PTVSD_LOG_DIR%
```

So I don't think the variable is flowing across `&&` in cmd, like it does in PowerShell.

@petepall, can you try [switching the terminal to PowerShell](https://code.visualstudio.com/docs/editor/integrated-terminal#_windows) and see if that produces the logs?

**Comment by int19h** [comment] 2019-05-24 22:24
Ah, my apologies, I didn't notice the bug title!

But this is definitely a problem, and I wonder if it is also related to the underlying issue - since all the `PYTHON...` variables are also not flowing through?

**Comment by int19h** [comment] 2019-05-24 22:29
False alarm, sorry- the expansion happens at the wrong time in my snippet because of the semantics of `%...%` (it expands before the whole thing executes). The variables do flow through.

**Comment by karthiknadig** [comment] 2019-05-25 00:50
@petepall Can you also try running this "cmd /C python.exe"? From both VSC terminal, and external command prompt and let us know what happens.

**Comment by petepall** [comment] 2019-05-25 11:52
@karthiknadig, when I run the command in the VSC terminal, I get the cmd.py that is opened up.
When I run the command in the external CMD window, I get python started.

Attached screenshot is showing both the VSC and the CMD results.
![image](https://user-images.githubusercontent.com/42099752/58368954-53873280-7ef4-11e9-9cfb-0fc9b4cbc2d0.png)

**Comment by petepall** [comment] 2019-05-25 11:53
Attached is also the requested log.
[debug15244.log](https://github.com/microsoft/ptvsd/files/3219358/debug15244.log)

**Comment by fabioz** [comment] 2019-05-25 12:11
It's as if `cmd.py` was marked as an executable file with an association to VSCode (it doesn't seem like the issue is in `ptvsd`, which doesn't seem to be even started).

Can you provide the output of your `PATH` environment variable on both (i.e.: `set PATH`) as well as the output of `where cmd` (in both)?

**Comment by petepall** [comment] 2019-05-25 17:15
@fabioz, the set Path gives:
`C:\WINDOWS\system32>set path
Path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Python37\;C:\Program Files\Python37\LIB\;C:\Program Files\Python37\Scripts\;C:\Users\PeterPallen\AppData\Roaming\Python\Python37\Scripts;C:\Users\PeterPallen\AppData\Roaming\Python\Python37\site-packages;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\PeterPallen\AppData\Local\Microsoft\WindowsApps;C:\Users\PeterPallen\AppData\Roaming\npm;C:\Users\PeterPallen\AppData\Local\Programs\Microsoft VS Code\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW `


Where CMD gives:
`C:\WINDOWS\system32>where cmd
C:\Windows\System32\cmd.exe
C:\Program Files\Python37\Lib\cmd.py`

**Comment by petepall** [comment] 2019-05-25 17:19
@fabioz, You hit the nail on the head, after looking at the where CMD, I saw that I have `C:\Program Files\Python37\Lib\cmd.py` looking at what is in the path, I saw that I had an entry for `C:\Program Files\Python37\LIB\`.

When I removed this setting, the debugger works correctly.

**Closed** 2019-05-25 17:21 UTC
Labels: Investigate

**Comment by fabioz** [comment] 2019-05-27 14:22
@DonJayamanne 

As a note, we probably wouldn't have this issue if the command line used was `cmd.exe` instead of just `cmd`.

Although the combination to do this may be unusual (a `cmd.py` to must be in a directory in the `PATH`, and as `.py` must be added to the `PATHEXT` so that it considers `.py` files executable), so, not sure if we'd like to fix that on the VSCode side or not (by using `cmd.exe` instead of just `cmd).
