### ISSUE TITLE
printing variable in debug mode doesn't show in the debug console anymore but in the terminal

### ISSUE THREAD

**Issue by amine4567** [microsoft/ptvsd#2089] opened 2020-02-14 09:23 UTC
## Environment data

- VS Code version: 1.42.1
- Extension version (available under the Extensions sidebar): 2020.2.63072
- OS and version: ubuntu 16.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): The bug is for both

## Expected behaviour

Printing a variable in debug mode would display its value in the debug console.

This does work on the 2019.11.50794 version of the python extension.

## Actual behaviour

The variable doesn't print in the debug console but in the terminal.

## Steps to reproduce:
Try printing any variable using print in debug mode using the latest version of the python extension.

Thanks.

**Comment by int19h** [comment] 2020-02-18 21:02
Dupe of #2036.

**Closed by int19h** 2020-02-18 21:02 UTC
