### ISSUE TITLE
Debugging WSGI app hangs

### ISSUE THREAD

**Issue by calebickler** [microsoft/ptvsd#2056] opened 2020-01-23 21:36 UTC
## Environment data

- PTVSD version: ms-python.python-2020.1.58038/pythonF
- OS and version: macOS Mojave 10.14.6
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.4 64-bit inside virtual environment made by tox
- Using VS Code or Visual Studio: VS Code

## Actual behavior

When making web request to debugging pyramid app request hangs and does not hit breakpoint added.

## Expected  behavior

Web request should hit endpoint

## Steps to reproduce:

````
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Pyramid Application",
      "type": "python",
      "request": "launch",
      "module": "pyramid.scripts.pserve",
      "args": [
        "${workspaceFolder}/development.ini"
      ],
      "env": {
        ...
      },
      "pyramid": true
    }
  ]
}
````

place breakpoint in endpoint, start up the debugger and hit the endpoint, request hangs and endpoint is not hit.

Callstack:
![image](https://user-images.githubusercontent.com/7074906/73025754-ffb34d00-3de4-11ea-986c-aeea25365233.png)

Interestingly it says paused on breakpoint ^ but my debug bar does now allow me to advance: 
![image](https://user-images.githubusercontent.com/7074906/73025809-1bb6ee80-3de5-11ea-9a62-48c8e87205e0.png)

another thing is that I can place my breakpoint in my `__init__.py` when the web app is starting and have it hit but not in the endpoint.

Here is the command the debugger is starting with ````(py37) sh-3.2$ env PTVSD_LAUNCHER_PORT=53433 /Users/cbickler/projects/src/adminsvc/.tox/py37/bin/python3.7 /Users/cbickler/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher -m pyramid.scripts.pserve /Users/cbickler/projects/src/adminsvc/development.ini ````

LMK if you need other info

**Comment by int19h** [comment] 2020-01-23 21:58
Can you please enable debugger logs via `"logToFile": true` in your launch.json, and then share the logs (`ptvsd*.log` and `pydevd*.log`) that it will produce in the directory where the extension is installed?

**Comment by calebickler** [comment] 2020-01-23 22:49
[ptvsd.adapter-67282.log](https://github.com/microsoft/ptvsd/files/4105953/ptvsd.adapter-67282.log)
[ptvsd.launcher-67287.log](https://github.com/microsoft/ptvsd/files/4105955/ptvsd.launcher-67287.log)
[ptvsd.server-67291.log](https://github.com/microsoft/ptvsd/files/4105956/ptvsd.server-67291.log)

**Comment by int19h** [comment] 2020-01-23 23:12
This is interesting. So it did hit the breakpoint, but the stack trace has no frames in it:
```
D+00008.969: /handling #64 event "stopped" from Server[2]/
             IDE[2] <-- {
                 "seq": 15,
                 "type": "event",
                 "event": "stopped",
                 "body": {
                     "reason": "breakpoint",
                     "threadId": 2,
                     "preserveFocusHint": false,
                     "allThreadsStopped": true
                 }
             }
...
D+00009.171: /handling #10 request "stackTrace" from IDE[2]/
             IDE[2] <-- {
                 "seq": 17,
                 "type": "response",
                 "request_seq": 10,
                 "success": true,
                 "command": "stackTrace",
                 "body": {
                     "stackFrames": [],
                     "totalFrames": 0
                 }
             }
```
Can you try running this with `"justMyCode": false` and see if that makes any difference for you? I wonder if we somehow end up treating your code as stdlib.

**Comment by calebickler** [comment] 2020-01-23 23:34
No luck, still doesn't hit the breakpoint

**Comment by int19h** [comment] 2020-01-23 23:58
Can you add `import traceback; traceback.print_stack()` at the point where you have the breakpoint, and share the output? We need to figure out why the frames aren't being reported...

Also, what happens if you double-click on MainThread in the thread list? Does the debug toolbar change?

**Comment by calebickler** [comment] 2020-01-24 00:10
Here is the traceback
````
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 155, in handle
    super(GeventWorker, self).handle(listener, client, addr)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/paste/deploy/config.py", line 291, in __call__
    return self.app(environ, start_response)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/smlib/log/__init__.py", line 427, in log_request_tween
    response = handler(request)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/rattr/tween.py", line 46, in __call__
    return self.handler(request)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/smlib/log/__init__.py", line 683, in wrapper
    return DefaultViewMapper.__call__(self, view)(context, request)
  File "/Users/cbickler/projects/src/adminsvc/.tox/py37/lib/python3.7/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/Users/cbickler/projects/src/adminsvc/adminsvc/lib/error_handler.py", line 33, in wrapper
    return func(*args, **kwds)
  File "/Users/cbickler/projects/src/adminsvc/adminsvc/views/v1/event_log_type.py", line 20, in get
    return self.event_log_type.get_event_types()
  File "/Users/cbickler/projects/src/adminsvc/adminsvc/models/event_log_type.py", line 13, in get_event_types
    traceback.print_stack()
````

If I double click on MainThread then the debug bar allows me to step over, step in, etc but the code is not highlighted at the breakpoint and if I step at all its just goes back to handing with nothing paused on breakpoint in the callstack window

**Comment by int19h** [comment] 2020-01-24 00:17
Ah, gevent is involved! This is likely a dupe of #1979. You're already using the new debugger, so all you need is to make sure that gevent debugging is enabled - `"gevent": true` in your launch.json should do the trick, since you're not attaching to an existing process. Does that fix it?

**Comment by calebickler** [comment] 2020-01-24 00:21
fixed it!

**Comment by calebickler** [comment] 2020-01-24 00:21
hmm, did I miss something that told me to use that?

**Comment by int19h** [comment] 2020-01-24 00:38
It's briefly mentioned in https://code.visualstudio.com/docs/python/debugging#_gevent, but it's not easy to find if you don't know what exactly you're looking for. 

@fabioz, is there any way we could provide improved diagnostics for these kinds of issues? I don't think we can check for gevent upfront, since it might not be imported. But maybe check for it at the points we know to be affected, like stack traces?

**Comment by fabioz** [comment] 2020-01-24 11:09
@int19h I think it should be possible to let the user know that if `gevent.monkey` is being used the `gevent` flag is needed (before halting the debugger).

I've created https://github.com/microsoft/ptvsd/issues/2057 to address this.

**Closed by fabioz** 2020-01-24 11:09 UTC

**Comment by calebickler** [comment] 2020-01-30 22:33
FYI now I can't debug my unit tests, tried having a different configuration for it:
````
    {
      "name": "Debug Tests",
      "type": "python",
      "request": "test",
      "console": "integratedTerminal",
      "justMyCode": true
    },
````

**Comment by int19h** [comment] 2020-01-30 23:21
If the tests also use gevent, that one will need the same flag here.

If it's not related to gevent, can you please file a separate issue?
