### ISSUE TITLE
Vscode Python Debugger extremly slow.

### ISSUE THREAD

**Issue by chrisaramar** [microsoft/ptvsd#1798] opened 2019-09-23 07:48 UTC
Hi, 

I've found a similar question but it has been loocked. 

I have to ask again because everything written there hasn't solved my problem.

My issue is the same. If I debug my python script in the vscode python debugger its extremly slow (About 20+ sec). 

But on cmd if I go to the path where the script is and execute it with the same python interpreter, it only needs 4 seconds. 

These are my launch settings:
![image](https://user-images.githubusercontent.com/55407727/65409028-fee2be00-dde6-11e9-9d53-44349b5f3cd0.png)

Edit: And my python and my vscode version are the latest ones.

**Comment by karthiknadig** [comment] 2019-09-23 18:17
@chrisaramar 
Can you provide some details on what OS, extension version, python version you are using?

**Comment by fabioz** [comment] 2019-09-23 18:32
5 times slower may not be that much depending on the use case, so, it'd be nice to have some code where we can reproduce it to know whether it's expected or not (note that even if expected we may be able to improve that use-case further).

Also, can you try to build the accelerator modules locally to see if it improves your particular use-case? (you can see: https://github.com/microsoft/ptvsd/issues/1741#issuecomment-527424685 for details)

**Comment by karthiknadig** [comment] 2019-09-23 19:45
Additionally, if there are certain areas you don't want to debug. you could wrap them with `ptvsd.tracing(False)` and `ptvsd.tracing(True)`. So, please share the requested details.

**Comment by chrisaramar** [comment] 2019-09-25 08:42
> @chrisaramar
> Can you provide some details on what OS, extension version, python version you are using?

OS is Windows 10 and Python is 3.7.4.

**Comment by chrisaramar** [comment] 2019-09-25 08:43
> 5 times slower may not be that much depending on the use case, so, it'd be nice to have some code where we can reproduce it to know whether it's expected or not (note that even if expected we may be able to improve that use-case further).
> 
> Also, can you try to build the accelerator modules locally to see if it improves your particular use-case? (you can see: [#1741 (comment)](https://github.com/microsoft/ptvsd/issues/1741#issuecomment-527424685) for details)

Yeah but the problem is not executing the script ... the thing which needs so much time is doing following stepps:

1. open terminal (if not already open)
2. enter the debug command
3. And then executing is a bit slower too but the most time is used for step 2 and 1

**Comment by chrisaramar** [comment] 2019-09-25 08:45
> 5 times slower may not be that much depending on the use case, so, it'd be nice to have some code where we can reproduce it to know whether it's expected or not (note that even if expected we may be able to improve that use-case further).
> 
> Also, can you try to build the accelerator modules locally to see if it improves your particular use-case? (you can see: [#1741 (comment)](https://github.com/microsoft/ptvsd/issues/1741#issuecomment-527424685) for details)

Also the problem is not the code because im not executing only one script ... the problem is with every script.

**Comment by chrisaramar** [comment] 2019-09-25 08:46
The main problem is starting the debugging workflow.

**Comment by karthiknadig** [comment] 2019-09-25 17:57
@chrisaramar we are aware of this issue. We are tracking cases to narrow down the cause for this.

@luabud This is another case of debugging taking too long to start.

**Comment by fabioz** [comment] 2020-02-04 11:38
@chrisaramar @karthiknadig do you know if this is still an issue?

**Comment by chrisaramar** [comment] 2020-02-04 12:19
Hi currently everything is working fine. So maybe they fixed something with the new version of vscode

**Comment by fabioz** [comment] 2020-02-04 12:24
Great ;)

I'm going to close this issue then. Please reopen if it happens again.

**Closed by fabioz** 2020-02-04 12:24 UTC
Labels: Performance

**Comment by jeromechungmf** [comment] 2020-07-15 07:23
maybe try pypy with vscode，it's can improve python debugger performance.
