### ISSUE TITLE
Venv, debugging, pythonpath broken

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1439] opened 2019-05-20 17:22 UTC
@ST33LDI9ITAL commented on [Sun May 19 2019](https://github.com/microsoft/vscode-python/issues/5690)

## Environment data

- VS Code version: 1.35.0-insider
- Extension version (available under the Extensions sidebar): 2019.4.12954
- OS and version: Win 10x64 10.0.17763
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.7.3 and WinPy 3.7.2
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv 
- Relevant/affected Python packages and their versions: XXX

## Expected behaviour

Venv to be detected and activated
Debugging to work with venv

## Actual behaviour

Doesn't detect or activate venv
Debugging doesn't work with venv, no breakpoints trip

## Steps to reproduce:
1. Set python path to "python.pythonPath": "${workspaceFolder}\\Scripts\\python.exe", 
Open python venv project folder, open any file, set breakpoints, run debug

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
Starting Microsoft Python language server.
##########Linting Output - pylint##########

--------------------------------------------------------------------

Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)



[Info  - 8:03:49 PM] GetCurrentSearchPaths c:\Dev\Python\examples\Scripts\python.exe 
[Info  - 8:03:49 PM] Python search paths:
[Info  - 8:03:49 PM]     c:\python\winpy\python-3.7.2.amd64\dlls
[Info  - 8:03:49 PM]     c:\python\winpy\python-3.7.2.amd64\lib
[Info  - 8:03:49 PM]     c:\python\winpy\python-3.7.2.amd64
[Info  - 8:03:49 PM]     c:\dev\python\examples
[Info  - 8:03:49 PM]     c:\dev\python\examples\lib\site-packages
[Info  - 8:03:49 PM] Configuration search paths:
[Info  - 8:03:53 PM] Microsoft Python Language Server version 0.2.82.0
[Info  - 8:03:53 PM] Initializing for c:\Dev\Python\examples\Scripts\python.exe
```

```


---

@webji commented on [Sun May 19 2019](https://github.com/microsoft/vscode-python/issues/5690#issuecomment-493829939)

Same issue:

Version: 1.35.0-insider (system setup)
Commit: 6ac87465f297a9068bf767f45d6f372fc5697de9
Date: 2019-05-17T17:48:07.036Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by karthiknadig** [comment] 2019-05-20 17:36
Dupe of #1440

**Closed by karthiknadig** 2019-05-20 17:36 UTC
