### ISSUE TITLE
It cannot print 16385 characters in one line at terminal.

### ISSUE THREAD

**Issue by humit0** [microsoft/ptvsd#2017] opened 2019-12-25 06:47 UTC
## Environment data

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): 2019.11.50794
- OS and version: Windows 10 Education 10.0.18362 Build 18362
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.1 32bit
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

## Expected behaviour

Expect to print 10 'C's at end of line.
![image](https://user-images.githubusercontent.com/8676247/71435183-3ab15a80-272b-11ea-93f3-64502582eb54.png)

## Actual behaviour

It only prints 'A'. So I think there are maximum character size when print one line.
![image](https://user-images.githubusercontent.com/8676247/71435138-0b9ae900-272b-11ea-91df-532ea0c401c4.png)

## Steps to reproduce:

1. Write below code & save it.
```python
s = 'A' * 0x4000 + 'C' * 10
print(s)
```

2. Press `Ctrl + F5` to run this file without debugging.

3. You can see the terminal output which there is no 'C'.

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
User belongs to experiment group 'ShowPlayIcon - start'
> conda --version
> pyenv root
> python3.7 -c "import sys;print(sys.executable)"
> python3.6 -c "import sys;print(sys.executable)"
> python3 -c "import sys;print(sys.executable)"
> python2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> py -3.7 -c "import sys;print(sys.executable)"
> py -3.6 -c "import sys;print(sys.executable)"
> py -3 -c "import sys;print(sys.executable)"
> py -2 -c "import sys;print(sys.executable)"
> python -c "import sys;print(sys.executable)"
> conda info --json
> ~\AppData\Local\Microsoft\WindowsApps\python.exe c:\Users\JJH\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python.exe c:\Users\JJH\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python3.exe c:\Users\JJH\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python3.exe c:\Users\JJH\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python.exe c:\Users\JJH\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python.exe c:\Users\JJH\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python3.exe c:\Users\JJH\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
> ~\AppData\Local\Microsoft\WindowsApps\python3.exe c:\Users\JJH\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\interpreterInfo.py
Starting Jedi Python language engine.
> conda --version
> ~\AppData\Local\Programs\Python\Python37-32\python.exe -m pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text f:\coding\twitchNotification\src\test.py
cwd: f:\coding\twitchNotification
> ~\AppData\Local\Programs\Python\Python37-32\python.exe -m pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text f:\coding\twitchNotification\src\test.py
cwd: f:\coding\twitchNotification
> ~\AppData\Local\Programs\Python\Python37-32\python.exe -c "import sys;print(sys.prefix)"
cwd: f:\coding\twitchNotification
> ~\AppData\Local\Programs\Python\Python37-32\python.exe -c "import sys;print(sys.prefix)"
cwd: f:\coding\twitchNotification
> ~\AppData\Local\Programs\Python\Python37-32\python.exe -c "import sys;print(sys.executable)"
cwd: f:\coding\twitchNotification
> ~\AppData\Local\Programs\Python\Python37-32\python.exe -c "import sys;print(sys.executable)"
cwd: f:\coding\twitchNotification
> ~\AppData\Local\Programs\Python\Python37-32\python.exe -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: f:\coding\twitchNotification
> ~\AppData\Local\Programs\Python\Python37-32\python.exe -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: f:\coding\twitchNotification
> ~\AppData\Local\Programs\Python\Python37-32\python.exe -m site --user-site
cwd: f:\coding\twitchNotification
> ~\AppData\Local\Programs\Python\Python37-32\python.exe -m site --user-site
cwd: f:\coding\twitchNotification
> ~\AppData\Local\Programs\Python\Python37-32\python.exe completion.py
cwd: c:\Users\JJH\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles
> ~\AppData\Local\Programs\Python\Python37-32\python.exe completion.py
cwd: c:\Users\JJH\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles
##########Linting Output - pylint##########

--------------------------------------------------------------------
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

There is no error log when running python code.

But in Debug Console, there exists 10 'C's.
![image](https://user-images.githubusercontent.com/8676247/71435721-9977d380-272d-11ea-8c9a-426d3ea5f4c9.png)

**Comment by fabioz** [comment] 2019-12-27 14:27
I can't reproduce this with the latest master (so, I think this is fixed in `ptvsd 5.x`).

@humit0 can you confirm which `ptvsd` version are you using?

You can create a file with the contents below and run it under the debugger to get the version.

```
import ptvsd
print(ptvsd.__version__)
```

**Comment by humit0** [comment] 2019-12-27 15:48
I change `.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\ptvsd_launcher.py` file code.
```python
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

import os
import os.path
import sys
import traceback

useCustomPtvsd = sys.argv[1] == '--custom'
ptvsdArgs = sys.argv[:]
ptvsdArgs.pop(1)

# Load the debugger package
try:
    ptvsd_lib_path = os.path.join(os.path.dirname(__file__), 'lib', 'python', 'old_ptvsd')
    if useCustomPtvsd:
        sys.path.append(ptvsd_lib_path)
    else:
        sys.path.insert(0, ptvsd_lib_path)
    try:
        import ptvsd
        print(ptvsd.__version__) # Add here
        from ptvsd.__main__ import main
        ptvsd_loaded = True
    except ImportError:
        ptvsd_loaded = False
        raise
except:
    traceback.print_exc()
    print('''
Internal error detected. Please copy the above traceback and report at
https://github.com/Microsoft/vscode-python/issues/new

Press Enter to close. . .''')
    try:
        raw_input()
    except NameError:
        input()
    sys.exit(1)
finally:
    if ptvsd_lib_path:
        sys.path.remove(ptvsd_lib_path)

main(ptvsdArgs)
```
I can check that `ptvsd` version is '4.3.2'.

**Comment by fabioz** [comment] 2019-12-27 16:27
Thanks for the confirmation. I'm marking as closed as this should be fixed in the current master version already (which is `ptvsd 5.x`).

**Closed by fabioz** 2019-12-27 16:27 UTC
