### ISSUE TITLE
Debug Console does not break lines

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [microsoft/ptvsd#1623] opened 2019-07-24 19:08 UTC
Issue Type: <b>Bug</b>

The debug console for python prints "\n" instead of breaking the line

Extension version: 2019.6.24221
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment] 2019-07-24 22:41
Dupe of #1432, which is due to https://github.com/microsoft/vscode/issues/73845.

@DonJayamanne, for future bugs about newlines in debug console, please direct users directly to https://github.com/microsoft/vscode/issues/73845, so that they can leave feedback there - there is a debate on that item about the correct behavior of the console in this case, so specific scenarios will help them decide how to resolve this properly.

**Closed by int19h** 2019-07-24 22:41 UTC
