### ISSUE TITLE
Hitting a breakpoint opens a new instance of the file

### ISSUE THREAD

**Issue by DeshmukhMalhar** [microsoft/ptvsd#2094] opened 2020-02-19 13:09 UTC
This issue is same as microsoft/vscode-python#5139, microsoft/vscode-python#225 and microsoft/vscode-python#4166
which closed and those suggest updating python ext, but mine is already up to date[2020.2.63072].

![image](https://user-images.githubusercontent.com/16190134/74835599-b6064580-5343-11ea-99ce-133f7351dea7.png)

Issues microsoft/vscode-python#5049 and microsoft/vscode-python#1313 are similar in nature.

and no, This is not the case of lowercase drive letters as said in https://github.com/microsoft/vscode-python/issues/2976#issuecomment-431946411

The problem here is that the breakpoints if marked in the original file, are carried over but can't be disabled from the new file. As well as breakpoints created in the new file are not migrated back to original file. i.e. the breakpoints are treated different. 

This leads to confusion in debugging as you just cannot see why the debugger is halting
If I want to remove a breakpoint, I have to use the breakpoints explorer. 

![image](https://user-images.githubusercontent.com/16190134/74835963-712ede80-5344-11ea-92d0-b1a112ad6ac7.png)
This is the look of breakpoints explorer in debugger

And by habbit , assuming that the file being debugged is displayed, I start editing the file and save it, which propagates the contents to the original file, but the breakpoints in the original file are now ordered very differently, thus making the debugger stop everywhere. Which is just annoying.

The steps to reproduce the issue are mentioned here : 
https://github.com/microsoft/vscode-python/issues/225#issue-273959633

and examples are here :
https://github.com/microsoft/vscode-python/issues/4166#issue-403825856

However, When I created a new Project, I was unable to produce the same result.
Then I thought that It may be because I have multiple Launch configurations in my project,
but testing with two launch configs in the new project does not seem to reproduce the issue.

I will try to provide as much info I can on this

The python interpreter is a conda env and code was started from conda powershell prompt in both cases

System Info:

AMD R7 1700 @3GHZ
RAM 16GB, 52% usage
Multiple HDDs and SSDs
VSCode version 1.42.1
![image](https://user-images.githubusercontent.com/16190134/74837056-a805f400-5346-11ea-9437-a114f8c6eb2c.png)

Python Extension version : 2020.2.63072

[conda_problem_env_packges_installed.txt](https://github.com/microsoft/vscode-python/files/4225212/conda_problem_env_packges_installed.txt)

EDIT:
UNRELETED:
Why is Github linking /pull/1313 at microsoft/vscode-python#1313 ?
![image](https://user-images.githubusercontent.com/16190134/74837895-7ee66300-5348-11ea-92d7-818e18f4e09a.png)

Where it links /issues/#<num> everywhere else?
![image](https://user-images.githubusercontent.com/16190134/74837907-84dc4400-5348-11ea-9379-6f6a43e5c4b9.png)

**Comment by fabioz** [comment] 2020-02-20 19:34
@DeshmukhMalhar do you have some kind of symlink or a subst drive there? Are you using a `pytest` run?

**Comment by int19h** [comment] 2020-02-20 19:34
The breakpoint misbehavior is fundamentally an issue with VSCode itself treating the two tabs as two different files, even though they're really the same. Changes in the editor propagate from one tab to the other, because they flow through the file itself. But breakpoints are metadata, and don't get the same accidental sync. But, in any case, the real problem is that the extra tab shows up in the first place, so let's try to figure that one out first!

Since you can repro it in one workspace but not another, it's likely to do with configuration. Can you please share the debug configuration from launch.json that you're using when the bug happens, and also the one for the project where things work fine?

Also, if you're using an "attach" configuration, then the command line used to start ptvsd would also come in handy.

**Comment by fabioz** [comment] 2020-02-20 19:39
p.s.: I'm asking about `pytest` specifically because it has an issue where it changes the working directory by resolving symlinks and substed drives, so, this could explain the issue... (see: https://github.com/pytest-dev/pytest/issues/5965)

**Comment by DeshmukhMalhar** [comment] 2020-02-21 05:30
> 
> 
> @DeshmukhMalhar do you have some kind of symlink or a subst drive there? Are you using a `pytest` run?

no symlink or subst.
I am not using pytest run

Here is a snippet of my launch.json
![image](https://user-images.githubusercontent.com/16190134/75006571-3047de80-5498-11ea-94f7-3b0370713480.png)




> 
> 
> The breakpoint misbehavior is fundamentally an issue with VSCode itself treating the two tabs as two different files, even though they're really the same. Changes in the editor propagate from one tab to the other, because they flow through the file itself. But breakpoints are metadata, and don't get the same accidental sync. But, in any case, the real problem is that the extra tab shows up in the first place, so let's try to figure that one out first!
> 
> Since you can repro it in one workspace but not another, it's likely to do with configuration. Can you please share the debug configuration from launch.json that you're using when the bug happens, and also the one for the project where things work fine?
> 
> Also, if you're using an "attach" configuration, then the command line used to start ptvsd would also come in handy.

the real problem is extra tab appearing.


Here is the command launching ptvsd 
![image](https://user-images.githubusercontent.com/16190134/75006871-5326c280-5499-11ea-9b41-ed30772028e5.png)

**Comment by DeshmukhMalhar** [comment] 2020-03-04 13:06
After 12 days from my reply, I don't see any updates.
Am I supposed to do anything more?

**Comment by karthiknadig** [comment] 2020-03-05 18:51
@DeshmukhMalhar sorry for the delayed reply. I think at this point we will need a way to repro this locally. If possible please share a minimal repro.

**Comment by DeshmukhMalhar** [comment] 2020-03-08 03:59
I tested this with another python file  in the same project, and I the tab duplication does not happen for it. I don't know why.

### Steps To reproduce :

1. Open a python file in vscode
2. Set some breakpoints
3. Start debug by pressing F5
4. I don.t know if a custom launch config makes any difference or not, but here is mine:
![image](https://user-images.githubusercontent.com/16190134/76156311-be6dc700-611e-11ea-8a07-2a19031efc13.png)

there are two args if it helps

### What should happen :
The debugger should start stepping through the same file on which it was launched on, not create a new file/tab.

**Comment by int19h** [comment] 2020-03-11 22:45
Are there any differences between the file for which you are seeing double tabs, and the one for which it doesn't happen? E.g. anything unusual about the filename, or a different path?

Perhaps there's any difference in which those files are getting executed by your main script? E.g. one is imported, and the other one is `execfile()`'d, or something similar?

**Comment by fabioz** [comment] 2020-03-12 11:01
@DeshmukhMalhar can you provide the logs for a session run where you have breakpoints in both versions of the file and it opens both after breakpoints hit?

Some notes on how to do that:

1. Please make sure that you're using the latest version of the debugger  (see: https://github.com/microsoft/ptvsd/issues/2104 to check how to do that).

2. Make a debug run and provide the logs.

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "logToFile": true
    },
```

* Start debugging
* When done, go back into the extension directory and upload the file debug*.log into this GitHub issue.

**Comment by int19h** [comment] 2020-05-04 19:49
We can't reproduce, so without the logs this isn't actionable. Please re-open if you're still having this problem and can share the logs.

**Closed by int19h** 2020-05-04 19:49 UTC
