### ISSUE TITLE
Issue starting debugger for Python and/or mixed debugging with conda

### ISSUE THREAD

**Issue by D-Roberts** [microsoft/ptvsd#2063] opened 2020-01-28 23:06 UTC
## Environment data

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): 2020.1.58038
- OS and version: macOS Catalina 10.15.2
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.6.8
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: not specific to a package
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): python.jediEnabled=true by default.

## Expected behaviour

Start debugger at first try.

## Actual behaviour
Debugger does not start. 

This is the error in the "Debug Console":

> Fatal Python error: PyCOND_WAIT(gil_cond) failed
Thread 0x0000700010c0f000 (most recent call first):
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 299 in wait
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 551 in wait
  File "/Users/denisaroberts/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 225 in _on_run
  File "/Users/denisaroberts/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 884 in _bootstrap

> Thread 0x000070001070c000 (most recent call first):
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 299 in wait
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 551 in wait
  File "/Users/denisaroberts/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 179 in _on_run
  File "/Users/denisaroberts/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 884 in _bootstrap

> Current thread 0x0000700010209000 (most recent call first):
  File "/Users/denisaroberts/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 270 in _read_line
  File "/Users/denisaroberts/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 287 in _on_run
  File "/Users/denisaroberts/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 884 in _bootstrap

> Thread 0x000070000fd06000 (most recent call first):
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 299 in wait
  File "/Users/denisaroberts/anaconda3/lib/python3.6/queue.py", line 173 in get
  File "/Users/denisaroberts/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 398 in _on_run
  File "/Users/denisaroberts/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
  File "/Users/denisaroberts/anaconda3/lib/python3.6/threading.py", line 916 in _bootstrap_inner

## Steps to reproduce:

1. Add the Extension to VSCode and enable.
2. Create settings.json with Pythonpath:
`{
    "python.pythonPath": "/Users/denisaroberts/anaconda3/bin/python"
}
   `

3. Create launch.json for mixed debugging (my use case is for mixed debugging Python/C++ code but the issue happens with only Python code as well):

> {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python launch",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "/Users/denisaroberts/anaconda3/bin/python3",
            "program":"${file}",
            "cwd":"${workspaceFolder}",
            "console": "internalConsole",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "justMyCode": false},
        {
            "name": "lldb attach Debug",
            "request": "attach",
            "program": "/Users/denisaroberts/anaconda3/bin/python3",
            "stopOnEntry": false,
            "pid": "${command:pickProcess}",
            "type": "lldb"
        }
    ]
}

4. Example code (specific code does not seem to affect the issue):

Python eg.py:

`import ctypes
import numpy
import glob
libfile = glob.glob('libProject.so')[0]
mylib = ctypes.CDLL(libfile)
mylib.mysum.restype = ctypes.c_longlong
mylib.mysum.argtypes = [ctypes.c_int, 
                        numpy.ctypeslib.ndpointer(dtype=numpy.int32)]
array = numpy.arange(0, 100000000, 1, numpy.int32)
array_sum = mylib.mysum(len(array), array
print('sum of array: {}'.format(array_sum))
`

C++ code mysum.cpp (irrelevant here but included for completeness):

`extern "C" 
long long mysum(int n, int* array) {
    // return type is 64 bit integer
    long long res = 0;
    for (int i = 0; i < n; ++i) {
        res += array[i];
    }
    return res;
}`

5. Add breakpoints in code.
6. Attempt start Python debugger: View ->Debug; select 'Python Launch'

**Comment by fabioz** [comment] 2020-01-30 10:27
This is a duplicate of https://github.com/microsoft/ptvsd/issues/2049 (it's already fixed and will be available in the next release). 

As a note, this issue only affects older versions of Python (Python 2.7 up to Python 3.6) -- so, if you can upgrade to use Python 3.7 or Python 3.8 this should work in the `ptvsd` version you already have there.

**Closed** 2020-01-30 10:28 UTC

**Comment by D-Roberts** [comment] 2020-01-30 18:47
@fabioz Will do, thanks.
