### ISSUE TITLE
vscode Django debug paused on breakpoint but not show variables

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1233] opened 2019-03-13 17:43 UTC
@nicebug commented on [Wed Mar 13 2019](https://github.com/Microsoft/vscode-python/issues/4737)

## Environment data

- VS Code version:1.32.1
- Extension version (available under the Extensions sidebar): 2019.2.5558
- OS and version: Mac OS 10.13.6
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.10
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Relevant/affected Python packages and their versions: XXX

## Expected behaviour
pause on breakpoint and show variables

## Actual behaviour

pause on breakpoint ,but no variables show 
<img width="517" alt="Screen Shot 2019-03-13 at 18 04 44" src="https://user-images.githubusercontent.com/1947907/54270811-357b8880-45bb-11e9-9c72-8865a61e69a5.png">

my launch.json for django is:
```
{
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "console": "integratedTerminal",
            "args": [
                "runserver",
                "--noreload"
                // "--nothreading"
            ],
            // "stopOnEntry": true,
            "django": true
        },
```

## Steps to reproduce:
1. XXX

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
no output msg
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
XXX
```

**Comment by fabioz** [comment] 2019-03-19 12:28
I can't reproduce this in the current master with a simple django project... (so, either it's already fixed or the use-case to reproduce needs more info).

@nicebug do you think you can provide a sample source code where this can be reproduced?

**Comment by nicebug** [comment] 2019-03-21 05:16
@fabioz  i use graphene , graphene-django. my project is a query for graphql. set a breakpoint on function resolve_xxx, it doesn't work as pic show. but in pycharm same project debug work

**Comment by nicebug** [comment] 2019-03-21 05:19
maybe  you can try a simple graphql django project..

**Comment by fabioz** [comment] 2019-03-25 16:50
I saw you commented out `"--nothreading"` on the launch config... if you add it back, does it work?

**Comment by jonespm** [comment] 2019-03-26 21:36
I was also seeing this issue on ptvsd 4.2.4 but 4.2.5 looks like it's working much better (so far) for me. Might want to try that out and see if it helps?

**Comment by nicebug** [comment] 2019-03-27 07:26
@fabioz   still not work , after add "--nothreading" back

**Comment by nicebug** [comment] 2019-03-27 10:17
@fabioz @jonespm  I try update vscode to 1.32.3, debug work!!  you can close the issue

**Comment by fabioz** [comment] 2019-03-27 10:22
Great, closing this issue ;)

**Closed by fabioz** 2019-03-27 10:22 UTC
Labels: Bug, Needs-more-info, Regression
