### ISSUE TITLE
Continue (F5) causes Could not find thread * if multi-threaded

### ISSUE THREAD

**Issue by medariox** [Microsoft/ptvsd#805] opened 2018-09-17 08:44 UTC
## Environment data

- PTVSD version: 4.1.1
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.14
- Using VS Code or Visual Studio: VS Code

## Actual behavior
After the first breakpoint, it's not possible to continue to the next one (Continue (F5)).

## Expected  behavior
Continue to the next breakpoint.

## Steps to reproduce:
After applying fix https://github.com/Microsoft/ptvsd/pull/758 it is possible to break correctly.
Set multiple break points. The first will break correctly, the second will output following message in the debug console:
```
Could not find thread *
Available: ['pid_10212_id_72621808', 'pid_10212_id_72243296', 'pid_10212_id_72621584', 'pid_10212_id_73150360', 'pid_10212_id_72697952', 'pid_10212_id_72541184', 'pid_10212_id_56967464']
```

**Comment by fabioz** [comment] 2018-10-02 15:08
Ok, I took a look at this and what's happening is the following:

- all threads are paused (first break)
- a continue is issued -- at this point, it will mark all threads to be run, but they aren't really running (they're just marked to run).
- one of those threads starts running, hits a breakpoint and pauses all existing threads -- at this point, other threads didn't get a chance to run at all, so, they don't send a `CMD_THREAD_RUN` nor a `CMD_THREAD_SUSPEND` as they didn't even leave the pause state, yet, the UI is seeing them in the `run` state, even though they haven't sent the related message.

Now, I'm not exactly sure this is the same issue as I couldn't hit that `Could not find thread *` condition, but it seems like it for me...

Steps to reproduce:

Create file with:

```
import threading

numbers = range(3)


def double(number):
    while True:
        doubled = number * 2
        print(doubled)
        import time
        time.sleep(.5)  # breakpoint here
    return doubled

threads = []
for num in numbers:
    thread = threading.Thread(target=double, args=(num,))
    thread.start()
    threads.append(thread)

for thread in threads:
    thread.join()
```

put breakpoint on the `# breakpoint here`, launch program, then after it hits the breakpoint hit continue a few times (at each time the `main thread` should always be running as it'll be effectively deadlocked in the `join`, but all the other ones should always be `suspended` -- or maybe temporarily running while on `time.sleep()` and the shortly thereafter should be `suspended`).

I'm not exactly sure of the best approach as this seems like an integration issue related to what the debug adapter protocol expects -- are backends expected to send spurious `continued` / `stopped` events even if they haven`t send a `continued` event?

I also noted that issuing a step next on one thread makes all other threads appear as running, which seems odd to me (so, those spurious events would need to be issued in that case too).

@karthiknadig @int19h a fix for this in the `pydevd` side could be generating those spurious `CMD_THREAD_RUN` and `CMD_THREAD_SUSPEND`, although this should probably be a new flag for `pydevd` as the current behavior shouldn't be broken does that seem Ok? The other option would be doing the needed bookkeeping in the `ptvsd` side.

**Comment by karthiknadig** [comment] 2018-10-03 18:33
VSC UI sees them as running because we return `allThreadsContinued` as a response for `continue` request. That can be fixed if we send `allThreadsStopped` as a part of the thread suspended event. Currently we do this only for VS and not for VSC. The issue here seems to be with bookkeeping in pydevd itself. 

@medariox can you provide the code where this issue repros, along with line where you set the break point?

**Comment by karthiknadig** [comment] 2018-10-19 20:02
This is not complete until https://github.com/Microsoft/ptvsd/issues/908 is done.

**Closed by karthiknadig** 2018-10-19 20:02 UTC
Labels: bug, upstream-pydevd
