### ISSUE TITLE
Python debugger variables display "Invalid variable attributes"

### ISSUE THREAD

**Issue by brainsqueeze** [microsoft/ptvsd#2105] opened 2020-03-05 18:34 UTC
Issue Type: <b>Bug</b>

## Expected results
Expect to see all attributes associated with all variables within the current debugger scope.

## Actual results
Most variable attributes are not accessible, and are instead replaced with "Invalid variable attributes". 

Extension version: 2020.2.64397
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.15.0-88-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.38GB (0.68GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

![vs-code-python-debugger](https://user-images.githubusercontent.com/10166255/76013471-ecb49200-5ee5-11ea-9701-a9ecbcb81514.png)

**Comment by int19h** [comment] 2020-03-13 00:18
Could you please share the output of `import ptvsd; print(ptvsd.__version__)` somewhere in your code?

**Comment by int19h** [comment] 2020-03-13 00:44
(likely dupe of #2080)

**Comment by brainsqueeze** [comment] 2020-03-13 10:51
@int19h the version is `'4.1.3'`. I am debugging inside of a Docker container and I am now realizing that I had frozen the ptvsd version on the requirements for the build. I have been debugging other projects that are not running inside of containers and the ptvsd version is not fixed, and those sessions display variables correctly. I will remove the ptvsd version requirement from the Docker build.

Seems like this ticket can likely be closed.

**Comment by int19h** [comment] 2020-03-13 18:14
Thanks! Feel free to reopen if it still repros for you.

**Closed by int19h** 2020-03-13 18:14 UTC
