### ISSUE TITLE
An error pops up when debug in Python3.7 with "Windows Application" option checked

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/ptvsd#2072] opened 2020-02-05 07:18 UTC
**VS version**
![image](https://user-images.githubusercontent.com/59192491/73819513-ae667d00-482a-11ea-9389-71d300ba031f.png)

**Steps to Reproduce**
1. Create Python Application project and type code
2. Right-click on the project and select Properties or press Alt+Enter to open Property page
3. Turn on the option "Windows Application" and change interpreter to Python3.7 in General tab and save
4. Start the debugger

**Expected behavior**
The code runs and can be debugged, and no terminal/console window appears. 
![image](https://user-images.githubusercontent.com/59192491/72881972-c45d4380-3d3c-11ea-825b-ea315cf191ac.png)

**Actual behavior**
**An error pops up in Python 3.7.**
![image](https://user-images.githubusercontent.com/59192491/73819134-df927d80-4829-11ea-8d98-669aef331f1e.png)

**Python 3.7 Log**
[Python37.txt](https://github.com/microsoft/ptvsd/files/4158036/Python37.txt)

**No response in Python 2.7 after starting debug.**
**Python 2.7 Log**
 
[Python27.txt](https://github.com/microsoft/ptvsd/files/4158037/Python27.txt)

**Comment by int19h** [comment] 2020-02-12 20:51
This looks like a dupe of #2052. We already have a fix for that issue, it just hasn't been shipped yet.

**Closed by int19h** 2020-02-12 20:51 UTC
