### ISSUE TITLE
Python debugger can't run

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#1076] opened 2018-12-20 20:16 UTC
@SmileGobo commented on [Thu Dec 20 2018](https://github.com/Microsoft/vscode-python/issues/3760)

## Environment data

- VS Code version: 1.30.1
- Extension version (available under the Extensions sidebar): Version: 2018.12.1
- OS and version: Linux Mint 17.1 Rebecca
- Python version: 3.6.3 64bit
- Type of virtual environment used : N/A 
- Relevant/affected Python packages and their versions: XXX
- Architecture: x64
## Expected Behavior
try run debug. In console show error (see below)

## Log
```
> cd /home/evgen/projects/ConnectionSwitcher ; env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" /usr/local/bin/python3 /home/evgen/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 34378 /home/evgen/projects/ConnectionSwitcher/src/ConnectionSwitcher.py
> Traceback (most recent call last):
>   File "/home/evgen/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/ptvsd_launcher.py", line 21, in <module>
>     import ptvsd
>   File "/home/evgen/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/__init__.py", line 13, in <module>
>     from ._vendored import force_pydevd
>   File "/home/evgen/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/force_pydevd.py", line 40, in <module>
>     'pydevd',
>   File "/home/evgen/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/__init__.py", line 123, in preimport
>     import_module(name)
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/home/evgen/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd_plugins/__init__.py", line 2, in <module>
>     __import__('pkg_resources').declare_namespace(__name__)
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1479, in <module>
>     register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
> AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

**Comment by fabioz** [comment] 2018-12-21 15:07
@karthiknadig you can close this issue (the issue is that the installed version of `pkg_resources` is broken, so, there's not much to do on `ptvsd`).

**Comment by SmileGobo** [comment] 2018-12-21 15:21
Yes you are right! I'm have broken envrivoment. I'm using pyenv for switch to python 3.6.7 and start vscode from console. That is work great. Thanks.

**Closed** 2018-12-21 18:48 UTC
Labels: bug, upstream-pydevd
