### ISSUE TITLE
Debugger crashes when dealing with unhandled exception in pypy

### ISSUE THREAD

**Issue by skamansam** [microsoft/ptvsd#1730] opened 2019-08-28 19:42 UTC
## Environment data

- VS Code version:  1.38.0-insider (Commit: 8cd00a7935eabef4aad0b0130b1d46daca0a47aa)
- Extension version (available under the Extensions sidebar):  2019.9.32808-dev
- OS and version: Linux x64 5.1.5-300.fc30.x86_64 (Fedora 30)
- Python version (& distribution if applicable, e.g. Anaconda): pypy3.6-7.1.1
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv
- Relevant/affected Python packages and their versions: any/all
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Language Server
- Electron: 4.2.9
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0

## Expected behaviour

The debugger continues without error when debugging files with custom exceptions.

## Actual behaviour

The debugger dies, as can be  seen in the console output. However, vscode still thinks the debugger session is active (the debug toolbar shows and the bottom status bar still shows debugging).

## Steps to reproduce:
1. Use the following code in an empty .py file:

```python
class MyError(Exception):
    def __init__(self, msg):
        print(msg)
        return Exception.__init__(self)
if __name__ == "__main__":
    raise MyError("HELP!")
```

Then run a debugger session, configured as such:
```json
{
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal"
    }
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)
```
[nothing but linter output]
```

Output from integrated terminal:

```
cd /home/sam/workspace/api-server ; /home/sam/.pyenv/versions/pypy3.6-7.1.1/bin/python /home/sam/.vscode-insiders/extensions/ms-python.python-2019.9.32808-dev/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 34593 /home/sam/workspace/api-server/tests/ptvsd_test.py 
HELP!
We've got an error while stopping in unhandled exception: <class '__main__.MyError'>.
Traceback (most recent call last):
  File "/home/sam/.vscode-insiders/extensions/ms-python.python-2019.9.32808-dev/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1740, in do_stop_on_unhandled_exception
    self.do_wait_suspend(thread, frame, 'exception', arg, is_unhandled_exception=True)
  File "/home/sam/.vscode-insiders/extensions/ms-python.python-2019.9.32808-dev/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 1615, in do_wait_suspend
    with self._threads_suspended_single_notification.notify_thread_suspended(thread_id, stop_reason):
  File "/home/sam/.pyenv/versions/pypy3.6-7.1.1/lib-python/3/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/home/sam/.vscode-insiders/extensions/ms-python.python-2019.9.32808-dev/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 360, in notify_thread_suspended
    with AbstractSingleNotificationBehavior.notify_thread_suspended(self, thread_id, stop_reason):
  File "/home/sam/.pyenv/versions/pypy3.6-7.1.1/lib-python/3/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/home/sam/.vscode-insiders/extensions/ms-python.python-2019.9.32808-dev/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 308, in notify_thread_suspended
    self.send_suspend_notification(thread_id, stop_reason)
  File "/home/sam/.vscode-insiders/extensions/ms-python.python-2019.9.32808-dev/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 354, in send_suspend_notification
    py_db.writer.add_command(py_db.cmd_factory.make_thread_suspend_single_notification(py_db, thread_id, stop_reason))
  File "/home/sam/.vscode-insiders/extensions/ms-python.python-2019.9.32808-dev/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py", line 294, in make_thread_suspend_single_notification
    py_db, thread_id, -1, set_additional_thread_info, self._iter_visible_frames_info, max_frames=-1)
  File "/home/sam/.vscode-insiders/extensions/ms-python.python-2019.9.32808-dev/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 1133, in build_exception_info_response
    while trace_obj.tb_next is not None:
AttributeError: 'NoneType' object has no attribute 'tb_next'
Terminated
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
[nothing happens when i run the debugger]
```

**Comment by gramster** [comment] 2019-08-29 17:24
I noticed that we check if the tb_next attribute exists in about half the cases but not in others. So at the very least we could be handling this more gracefully.

**Comment by fabioz** [comment] 2019-08-29 17:44
I'll take a look at this.

**Comment by fabioz** [comment] 2019-08-30 11:15
Just to note, I took a look and the issue only happens in pypy not in CPython, so, I'm changing the title to reflect that.

**Comment by fabioz** [comment] 2019-09-02 18:13
I'm still investigating this issue... 

The problem isn't really not having a `tb_next` (that is just masquerading the real problem which is a bug in PyPy... I created a bug report for the real cause at: https://bitbucket.org/pypy/pypy/issues/3067/error-getting-locals-for-frame-from-a).

Checking for the `tb_next` does improve the situation a bit in that the debugger won't crash at that place, but it'll still report an unknown exception, whereas the exception should be known.

Also, this can be reproduced without custom exceptions in PyPy. i.e.: the code below will already trigger the error.

```
if __name__== '__main__':
    raise Exception('foo')
```

-- we do have tests for that already, but we don't currently run tests against PyPy, so, the first step would be putting PyPy in the ci.

Also, I'm still investigating the best workaround against this issue in PyPy (I'm a bit unsure whether we should just report as unknown for now and let PyPy fix the real bug or if we should provide a workaround that's more complete and would allow reporting the exception type but would also add more complexity to the debugger itself -- I'll probably do the simplest fix just so that we don't crash and wait for an update from the PyPy team regarding that issue).

**Comment by fabioz** [comment] 2019-09-03 19:43
I'm closing this one as a duplicate of https://github.com/microsoft/ptvsd/issues/835 (we should workaround through the related PyPy issue to fix that and there are already tests for this scenario).

**Closed by fabioz** 2019-09-03 19:43 UTC
Labels: Bug, Unplanned-work
