### ISSUE TITLE
Reattach not working when launching a program for debugging using ptvsd.enable_attach

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#516] opened 2018-06-23 16:54 UTC
* Create a python program and enable remote debugig using `ptvsd.enable_attach`
```python
import ptvsd
import time

ptvsd.enable_attach()

for i in range(1000):
    time.sleep(1)
    print(i)
```
* Attach, then detach
* Attaching once again fails.

**Comment by karthiknadig** [comment] 2018-06-23 20:42
Dupe of #472

**Closed by karthiknadig** 2018-06-23 20:42 UTC
Labels: bug

**Comment by DonJayamanne** [comment] 2018-06-24 00:40
@karthiknadig
Lol, you really need to provide more info on the issues you create, to prevent such dups. Cuz I thought that issue was for attaching programs launched using `python -m ptvsd ...`

**Comment by DonJayamanne** [comment] 2018-06-24 00:53
Note I'm not getting any warning messages when disconnecting in VSC. Hence not sure they are the same.

**Comment by karthiknadig** [comment] 2018-06-24 02:48
@DonJayamanne I had put `enable_attach` in the title, so I am not sure how it could be confused with `-m ptvsd ...`. I agree I should have provided the repro code. I didn't feel it was necessary at the time given this issue occurs with basic `enable_attach`. 

When I created the issue, the #398 was still open, it could have been a side effect of that issue.

**Comment by DonJayamanne** [comment] 2018-06-24 19:18
My bad didn't read the title carefully enough.

**Comment by ericsnowcurrently** [comment] 2018-06-26 18:45
This appears to be fixed with #527.
