### ISSUE TITLE
Debug restart not working

### ISSUE THREAD

**Issue by DaiZack** [microsoft/ptvsd#2071] opened 2020-02-03 01:25 UTC
Issue Type: <b>Bug</b>

When using debug restart button, it actually quit the the debug rather than restart

Extension version: 2020.1.58038
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|15.89GB (9.53GB free)|
|VM|0%|
</details>

**Comment by int19h** [comment] 2020-02-03 22:50
Likely dupe of #2029. Can you do `print(ptvsd.__version__)` to check that it's 5.0.0a11 or earlier? a12 has the fix.

**Comment by karthiknadig** [comment] 2020-02-09 20:19
`2020.1.58038` shipped with `5.0.0a11`

**Closed by karthiknadig** 2020-02-09 20:19 UTC
