### ISSUE TITLE
No possibility to remote debug on folders mounted through WinSSHFS

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/ptvsd#1349] opened 2019-04-11 17:35 UTC
@filipski commented on [Wed Apr 10 2019](https://github.com/Microsoft/vscode-python/issues/5193)

Copy from https://github.com/Microsoft/vscode/issues/72070 where it was suggested it's an extension issue, so I guess it's the vscode-python causing the problem.

Issue Type: <b>Bug</b>

Up until today morning, remote debugging on Python with ptvsd was working fine. Then I got 1.33 update and none of my breakpoints can be found anymore, I get warnings like:

`pydev debugger: warning: trying to add breakpoint to file that does not exist: /home/<my username>/projects/<my project folder>/v:/projects/<my project folder>/<python file to debug>.py (will have no effect)`

I have my remote Linux home folder mounted on Windows with WinSSHFS as a V: drive. 
I made no other changes to the environment (no manual update of the extensions) nor the project, just allowed installation of 1.33.0 VSCode update. 
I had ptvsd 4.2.6 in my remote conda environment before the VSCode update but I tried updating to 4.2.7 - the breakpoints still don't work.

Please fix asap as it's preventing me from remote debugging efficiently.

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (24.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
restructuredtext|lex|106.0.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.3.6558
vscode-yaml|red|0.4.0

</details>

**Comment by fabioz** [comment] 2019-04-11 17:39
@filipski This is a duplicate of https://github.com/Microsoft/ptvsd/issues/1311.

Please see the comment: https://github.com/Microsoft/ptvsd/issues/1311#issuecomment-481231104 for details on how to specify the `remoteRoot` properly so that this doesn't occur.

**Closed by fabioz** 2019-04-11 17:39 UTC

**Comment by filipski** [comment] 2019-04-13 20:00
Thanks for the link, I confirm than setting manually localRoot to a path with proper casing instead using `${workspaceFolder}` works around the problem. I hope that the original issue will be fixed soon, too. It's simply easier not to have to set this manually.
