### ISSUE TITLE
Using new version of PTVSD displays error message in terminal

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1638] opened 2019-07-27 20:51 UTC
## Environment data

- PTVSD version: 4.3.0
- OS and version: Mac
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3
- Using VS Code or Visual Studio: Latest or Insider

## Actual behavior

When debugging the following message is displayed in the terminal:
`Unable to find threadStateIndex for the current thread. curPyThread: 0x7fd019c05e60`

## Expected  behavior

No messages

## Steps to reproduce:
1. Install latest VS Code
2. Pip install latest PTVSD into python environment
3. Debug with custom `launch.json` ensuring the custom PTVSD is used
I.e. add the following into `launch.json`:
```js
"customDebugger": true
```

**Comment by fabioz** [comment] 2019-07-28 20:31
This is a duplicate of https://github.com/microsoft/ptvsd/issues/1587 (my plan is to tackle that when I'm back from vacations... after August 5th).

**Closed by fabioz** 2019-07-28 20:31 UTC

**Comment by brando90** [comment] 2020-04-28 15:00
> ## Environment data
> * PTVSD version: 4.3.0
> * OS and version: Mac
> * Python version (& distribution if applicable, e.g. Anaconda): 3.7.3
> * Using VS Code or Visual Studio: Latest or Insider
> 
> ## Actual behavior
> When debugging the following message is displayed in the terminal:
> `Unable to find threadStateIndex for the current thread. curPyThread: 0x7fd019c05e60`
> 
> ## Expected behavior
> No messages
> 
> ## Steps to reproduce:
> 1. Install latest VS Code
> 2. Pip install latest PTVSD into python environment
> 3. Debug with custom `launch.json` ensuring the custom PTVSD is used
>    I.e. add the following into `launch.json`:
> 
> ```js
> "customDebugger": true
> ```

how did you get the debugger version number?
