### ISSUE TITLE
Debug pytest parametrized test

### ISSUE THREAD

**Issue by rubenhelsloot** [microsoft/ptvsd#2061] opened 2020-01-15 06:53 UTC
## Environment data

- VS Code version: 1.41.1
- Extension version (available under the Extensions sidebar): 2020.1.58038
- OS and version: MacOS 10.14.6
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pipenv
- Relevant/affected Python packages and their versions: pytest 5.3.2
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Jedi enabled

## Expected behaviour

When pressing the grey "Debug Test (Multiple)" link above a test, a dropdown opens where I can select a single test or all tests to run. When I make a selection, the terminal opens a debug session where the command `pytest "<my test.py>::<my test>[my-test-parameters]"` is run.

## Actual behaviour

Instead of the above, the terminal opens a debug session where the command `pytest <my test.py>::<my test>[my-test-parameters]` without quotes is run. In the below example, this fails with `no matches found: ./tests/test_integers.py::test_integers[0]`, I think it's because of the square brackets, which are special characters in bash.

## Steps to reproduce:
This minimal example succeeds when pressing "Run Test", but fails when pressing "Debug Test".
```
@pytest.mark.parametrize(
    "i",
    [0]
)
def test_integers(i: int):
    assert int(i) == i
```

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
XXX
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
XXX
```

**Comment by rubenhelsloot** [comment] 2020-01-29 09:22
Hi @karthiknadig I think I found the cause. I was able to run your code, no problem, but when I decided to add the `logToFile` line to my setup, it failed. Toggling all values off and on found that `"console": "integratedTerminal"` sends an invalid command to the terminal, which it then cannot process.

**Comment by int19h** [comment] 2020-01-29 20:06
It looks like the "runInTerminal" request is formed correctly, but then VSCode doesn't escape the brackets properly. To clarify - with the above log, you're seeing this in the terminal?
```
/Users/rubenhelsloot/data-warehouse/.venv/bin/python ... ./tests/test_foo.py::test_integers[0]
```
i.e. without the quotes for that last argument?

**Comment by rubenhelsloot** [comment] 2020-01-29 21:07
Yes exactly, that is what I tried to explain in sections expected and actual behaviour, sorry if that wasn't clear

**Comment by int19h** [comment] 2020-01-29 21:59
I don't think square brackets are the problem per se. This works as expected for me in Bash:
```
python3 -m pytest ./tests/test_foo.py::test_integers[0]
```
However, this is a relative path, so it's only valid for a specific directory. When that command is run in the terminal, what is the current directory for the shell?

**Comment by int19h** [comment] 2020-01-29 22:05
Actually nevermind, I see that it includes `"cwd": "/Users/rubenhelsloot/data-warehouse"` in the launch request, so it would override whatever is current in the shell.

Can you confirm that it's the correct path, though? i.e. that the file is at `/Users/rubenhelsloot/data-warehouse/tests/test_foo.py`?

**Comment by rubenhelsloot** [comment] 2020-01-30 18:30
Yes, that's right

**Comment by int19h** [comment] 2020-02-19 23:41
Still can't reproduce it... can you please share the complete "test" configuration that you have in your launch.json?

Also, among the log files generated when running with `"logToFile": true`, there should also be one named `ptvsd.launcher...log` - can you share that one as well?

**Comment by int19h** [comment] 2020-04-07 18:32
Unable to reproduce without additional information - closing for now.

**Closed by int19h** 2020-04-07 18:32 UTC
Labels: Bug
