### ISSUE TITLE
Python debugger freezes on fast.ai functions

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#1254] opened 2019-03-20 17:56 UTC
@alexanderschiffhauer commented on [Tue Mar 19 2019](https://github.com/Microsoft/vscode-python/issues/4840)

Issue Type: <b>Bug</b>

I've found that the Python debugger hangs on numerous fast.ai functions. In this case, the debugger always hangs on `unet_learner(...).fit_one_cycle(...)`. I've also seen the debugger to hang on the other training-related methods in the API (e.g. `unet_learner(...).fit(...)`

Note that if I run this code without the debugger, the entire Python script properly executes and I end up with a PyTorch neural network. Moreover, debugging this code on PyCharm works, as well. I've tested this code on VSCode and PyCharm on Mac and Linux, Python 3.7.2, and the results were consistent -- using the same environment, the Python script froze during VSCode debugging but not PyCharm debugging (and did not freeze when run without a debugger).

Extension version: 2019.2.5558
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.18.0-16-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3906)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.59GB (4.48GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by fabioz** [comment] 2019-03-20 18:02
@alexanderschiffhauer can you provide some standalone code sample with instructions to reproduce this?

**Comment by alexanderschiffhauer** [comment] 2019-03-21 04:18
Here's a standalone example. The only dependency should be the fast.ai SDK:

`pip3 install fastai`
`python3 segmentation.py` <-- this should run fine

On the other hand, if you debug the file (e.g. current file, integrated terminal) the debugger will hang.

[vscode-bug.zip](https://github.com/Microsoft/ptvsd/files/2990811/vscode-bug.zip)

**Comment by fabioz** [comment] 2019-03-22 14:00
It seems this is actually a dupe of https://github.com/Microsoft/ptvsd/issues/943

For me, adding the code below makes it work on Python 3.6:

```
import multiprocessing
multiprocessing.set_start_method('spawn', True)
```

**Closed by fabioz** 2019-03-22 14:00 UTC
Labels: Investigate
