### ISSUE TITLE
AssertionError: Paths passed to _NormPaths must be str.

### ISSUE THREAD

**Issue by medariox** [Microsoft/ptvsd#804] opened 2018-09-17 07:15 UTC
## Environment data

- PTVSD version: 4.1.1
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.14
- Using VS Code or Visual Studio: VS Code

## Actual behavior
Starting the debugger spams the debug console with this exception:
```
Traceback (most recent call last):
  File "c:\Users\Dario\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 289, in __call__
    if not py_db.in_project_scope(filename):
  File "c:\Users\Dario\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 297, in in_project_scope
return pydevd_utils.in_project_roots(filename)
  File "c:\Users\Dario\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_utils.py", line 251, in in_project_roots
    filename = _normpath(filename)
  File "c:\Users\Dario\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_utils.py", line 19, in _normpath
    return pydevd_file_utils.get_abs_path_real_path_and_base_from_file(filename)[0]
  File "c:\Users\Dario\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 503, in get_abs_path_real_path_and_base_from_file
    abs_path, real_path = _NormPaths(f)
  File "c:\Users\Dario\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd_file_utils.py", line 224, in _NormPaths
    raise AssertionError('Paths passed to _NormPaths must be str. Found: %s (%s)' % (filename, type(filename)))
AssertionError: Paths passed to _NormPaths must be str. Found: d:\python27\lib\queue.py (<type 'unicode'>)
```

## Expected  behavior
Don't raise the exception.

## Steps to reproduce:
This behaviour was introduced with PR https://github.com/Microsoft/ptvsd/pull/660. We use `from future import unicode_literals` to provide cross compatibilty between Python 2/3. This causes the paths to be unicode, which works perfectly fine. Removing this condition fixes the issue: https://github.com/Microsoft/ptvsd/pull/660/files#diff-0f5096650b259df4ec84c21f5889eadbR204

**Comment by fabioz** [comment] 2018-09-17 12:04
Hi, thanks for the report...

Regarding the condition, unfortunately, it can't just be plainly removed (the filename must really be str on py2 and str on py3 because it'll be compared in other places with that type -- it's expected that `frame.f_code.co_filename` is `str`, even if you add a `from future import unicode_literals`).

So, what must be fixed is that the filename that gets there is really of the `str` type (although I'm puzzled on how that actually happened -- this needs a bit more investigation on how the filename gotten at https://github.com/Microsoft/ptvsd/blob/master/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py#L284 is unicode -- it should always be a `str` there).

As a note, in https://github.com/Microsoft/ptvsd/pull/660/files#diff-0f5096650b259df4ec84c21f5889eadbR205 we check that filename is actually str when it gets there (although in this case something got lost after normalizing -- we should probably do a new check for the type of the file just before putting it in the cache to make sure that it's still the expected type, which would point the actual place which stored the wrong type).

So, let's see if we can try to discover why this happens in your case (so, some questions which may help finding the root cause).

Can provide some sample code to reproduce this? 

Can you reproduce this in all launches (i.e.: launching a simple `print('hello world')` also fails)? 

Which libraries do you depend on?

Do you by any chance monkey-patch any functions from `os.path` to return unicode?

**Comment by medariox** [comment] 2018-09-17 13:15
Thank you for the prompt reply!

Yes, we do indeed monkey-patch [quite a few](https://github.com/pymedusa/Medusa/blob/master/medusa/init/filesystem.py#L128-L130) `os.path` functions. We do that because Python 2 is incredibly inconsistent regarding what type (`str`/`unicode`) is returned by these functions. I have been using `ptvsd` for quite some time and never actually experienced any issues before this change. From a quick look I wasn't able to find out which parts **need** to be `str` instead of `unicode`. Maybe we can figure out a way to make it work, instead of raising the exception? I understand that ours might be an edge case, but it would be great if we could keep using VS Code with unicode paths nonetheless.

**Comment by fabioz** [comment] 2018-09-17 13:54
Well, if you use only ascii chars everywhere, it should usually work on Py2 (because it automatically converts bytes<->unicode), but if you use non ascii chars for your files (or a folder which has your files), you'll have problems.

There are a number of `os.path` uses and the debugger expects to be able to use such basic machinery from Python (i.e.: https://github.com/Microsoft/ptvsd/search?q=os.path&unscoped_q=os.path -- in general, if one of those enters bytes it should also exit bytes and if it enters unicode it should exit unicode... if one of those doesn't and you monkey patch to have that behavior, I think it may still be Ok, but if you patch to enter bytes and exit unicode, the breakage is expected).

Personally, I think the fix should be in your code... instead of changing os.path globally create your own version which does what you need and change your own uses of os.path to your version or try to make it consistent regarding the type that enters and exits the function (there are probably many other libraries which expect os.path to enter/exit bytes and they'd also break with that change).

**Comment by medariox** [comment] 2018-09-18 20:54
You are absolutely right and that's also all we do in our monkey-patched `os.path` functions. We make sure that the input is a byte string and as soon as we get the output we decode it to unicode, so that we can work with it in our (`from future import unicode_literals`) code without any issues. We do this to avoid having to convert every single `os.path` input + output in our code which, considering our large codebase, wouldn't be very practical nor functional. I don't think that there is anything to change in our code (other than maybe dropping support for Python 2), but I understand if you are not willing to suppress or at least limit (e.g. to the first time) the exception - at the end of the day it's your code and you have to maintain it.

**Comment by karthiknadig** [comment] 2018-10-09 18:37
Closing this for now. Please re-open if needed.

**Closed by karthiknadig** 2018-10-09 18:37 UTC
