### ISSUE TITLE
Debug console cannot line feed

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1471] opened 2019-05-28 17:49 UTC
@DindoW commented on [Mon May 27 2019](https://github.com/microsoft/vscode-python/issues/5797)

Issue Type: <b>Feature Request</b>

When I debug a python program, I wish arrays are in alignment.
But the debug console dosen't line feed though there is a '\n' in the end of the array.
Generally, the output of the debug console should be on every 5 elements in a row, and now, they are crowded together.

see:
![捕获](https://user-images.githubusercontent.com/24449181/58423726-5f2b5280-80c8-11e9-96b8-c0687f855368.PNG)

Extension version: 2019.4.12954
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

**Comment by int19h** [comment] 2019-05-28 17:50
Dupe of #1432

**Closed by int19h** 2019-05-28 17:50 UTC
