### ISSUE TITLE
[Feature Request] "Edit and Continue" for debugging (reloaded)

### ISSUE THREAD

**Issue by janosh** [microsoft/ptvsd#1463] opened 2019-05-23 14:03 UTC
#165 was closed with the statement that Python does not allow for ["edit and continue" functionality](https://docs.microsoft.com/en-us/visualstudio/debugger/edit-and-continue) in debug session.

Looking on Stackoverflow, however, [people seem to have found generic workarounds](https://stackoverflow.com/a/24637113/4034025) for making it work in PyCharm. It sounds like reloading/reimporting a modified module during a debug session should be possible in VS Code as well, no?

**Comment by brettcannon** [comment] 2019-05-23 17:39
Moving this to ptvsd to see if this is somehow feasible now.

**Comment by karthiknadig** [comment] 2019-05-23 18:11
Dupe of #1192.

Note: we have had this discussion in the debugger team. This is a very big item, for now the priority on this is low. We definitely plan on looking into this.

**Closed by karthiknadig** 2019-05-23 18:11 UTC
