### ISSUE TITLE
Debugger always breaks into handled exceptions in remote debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/ptvsd#580] opened 2018-07-03 21:12 UTC
## Environment data

- PTVSD version: Master
- OS and version: N/A (but tested on Windows)
- Python version (& distribution if applicable, e.g. Anaconda): XXX
- Using VS Code or Visual Studio: VSC
- Though this is remote debugging, everything is local, both debugger and program

## Actual behavior
Debugger breaks into handled exceptions with the setting `Raised Exceptions` turned off.
 
## Expected  behavior

Debugger should not break into handled exceptions with the setting `Raised Exceptions` turned off.

This used to work in `4.1.1a5`

## Steps to reproduce:
* Start the following code for remote debugging:
```python
import time

import ptvsd
ptvsd.enable_attach()

for i in range(1000):
    time.sleep(1)
    print(i)
    try:
        raise ArithmeticError()
    except Exception:
        pass
```
* Go into VSC
* Ensure the settings in `Breakpoints` of VSC are as follows (default):
[ ] Raised Exceptions
[x] Uncaught Exceptions
* Attach the debugger (for remote debugging)
* Observe how debugger breaks on the exception

VSC `launch.json` configuration: (change the `<host-name>`)
```json
        {
            "name": "Python Experimental: Attach",
            "type": "pythonExperimental",
            "request": "attach",
            "port": 5678,
            "host": "<host-name>",
            "redirectOutput": true
        },
```

**Comment by karthiknadig** [comment] 2018-07-09 20:28
Does not repro on Windows and Linux.

**Comment by karthiknadig** [comment] 2018-07-10 20:04
@fabioz Looks like we call  into `trace_unhandled_exceptions` for handled exceptions. This is only occurring when script is launched like `python3 one.py`, but not when it is lauched as a module `python3 -m one`
```
  File "one.py", line 13, in <module>
    raise ArithmeticError()
  File "C:\GIT\ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_trace_dispatch_regular.py", line 177, in trace_unhandled_exceptions
    traceback.print_stack()
```
Can you take a look at this?

**Comment by fabioz** [comment] 2018-07-10 20:35
Ok, will take a look at it.

**Comment by fabioz** [comment] 2018-07-11 13:08
Ok, the problem is: for dealing with unhandled exceptions, `pydevd` will trace the topmost frames for exceptions (which is usually inside `pydevd` itself when launched from `pydevd` or some thread which started from `threading`). 

Now, when the user starts without the debugger in place and does an attach, the debugger is already very late to do any monkey-patching, so, it resorts to tracing the topmost frame available from the user code (which is the user code itself when the user launches the script directly or `runpy` when the user launches using the `-m` switch -- which is why it's only an issue when the user launches using the script).

Python itself provides no way for the debugger to know whether it's dealing with an exception that's unhandled or another which is handled.

i.e.: considering the code with the tracing on:

```
import sys

def trace_dispatch(frame, event, arg):
    print('Frame: %s, Line: %s, Event: %s, Arg: %s' % (frame.f_code.co_filename, frame.f_lineno, event, arg))
    return trace_dispatch

sys.settrace(trace_dispatch)
frame = sys._getframe()
while frame:
    frame.f_trace = trace_dispatch
    frame = frame.f_back

try:
    raise ArithmeticError()
except Exception:
    pass
```

The output with a try..except in place is something as:
```
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 11, Event: line, Arg: None
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 9, Event: line, Arg: None
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 13, Event: line, Arg: None
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 14, Event: line, Arg: None
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 14, Event: exception, Arg: (<type 'exceptions.ArithmeticError'>, ArithmeticError(), <traceback object at 0x0000000002D70108>)
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 15, Event: line, Arg: None
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 16, Event: line, Arg: None
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 16, Event: return, Arg: None
```

and the output without a try..except in place is something as:

```
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 11, Event: line, Arg: None
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 9, Event: line, Arg: None
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 13, Event: line, Arg: None
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 13, Event: exception, Arg: (<type 'exceptions.ArithmeticError'>, ArithmeticError(), <traceback object at 0x0000000003470108>)
Frame: W:\runtime-pydev.debugger\check\check_unhandled_root.py, Line: 13, Event: return, Arg: None
```

So, the point where the exception is raised, only appears once in the debugger and it's similar in both cases. In this case, as the debugger knows that it's in a topmost frame it decides to handle that exception (even though it's in a try..except block). In order to solve this issue, the debugger would need to know that it's inside a try..except block and which is the exception caught by it, but this is not trivial to know.

Python itself has a similar situation when setting a new frame.f_lineno (i.e.: https://github.com/python/cpython/blob/master/Objects/frameobject.c#L89) and it does that by using the bytecode... we'd need to do something similar (but supporting the bytecode of all versions of Python we're interested) or parsing the source code itself to look for try..except constructs (or maybe use `sys.excepthook` for exceptions from the main thread -- `pydevd` used to do this -- the bad thing is that it may be user-assigned, so, it was not uncommon for the user to loose that tracing altogether and it won't work in any other case, just for the main thread exiting).

Ideally Python itself would provide the `return` event with an exception arg, but it doesn't... maybe something nice to add to CPython itself in a future release ;)

Anyways, my current feeling is that given that this is a corner case (it only happens when it's in a caught exception in the topmost frame on a remote attach), and given that the actual solution is hard to implement, I'm inclined to leaving this as is for now (but if you feel it's really high-priority, I can take a look at one of the approaches I mentioned before) 

Note 1: there are other cases where topmost frames appear besides the main entry point -- i.e.: `QThreads` and `greenlets` and they'd have the same limitations (those wouldn't be solved by the `sys.exceptook`, only by analysing the bytecode or source code).

Note 2: I don't think this is a regression (I took a brief look at ptvsd 3 and it seems to check if it's a topmost frame to detect if it's handled or unhandled: https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/ptvsd/debugger.py#L485).

**Comment by DonJayamanne** [comment] 2018-07-11 16:22
**Here's why its a regression to me (it didn't happen earlier):**
* This regression was introduced in 
    * Commit: d635e22d3396f1cf3ab2fe9bc6fc9f5395b38232, 
    * PR: [Fixes issues dealing with handled and unhandled exceptions (#114, #446). (#471)](https://github.com/Microsoft/ptvsd/pull/471)

**Evidence (3 separate scenarios):**
* Clear [Raised Exceptions] & [Uncaught Exceptions], nothing will happen
* Select only [Uncaught Exceptions], only break on uncaught exceptions
* Select both [Raised Exceptions] & [Uncaught Exceptions], breaks on both exceptions

![exhandling](https://user-images.githubusercontent.com/1948812/42585644-13d53352-84eb-11e8-8b66-527854b31926.gif)

**Comment by fabioz** [comment] 2018-07-11 16:30
@DonJayamanne if you want I can still use `sys.excepthook` for the main thread (which as I mentioned is what was used before, but still, this isn't ideal and the user could break it if it reassigned it (which is actually pretty common -- i.e.: https://github.com/search?q=%22sys.excepthook+%3D%22&type=Code), so, IMHO, for most real-world code (where usually interesting code starts in a `main()` function) the current approach is better (even if a regression if all the code lives in the topmost code).

**Comment by ericsnowcurrently** [comment] 2018-07-11 17:29
> Ideally Python itself would provide the return event with an exception
> arg, but it doesn't... maybe something nice to add to CPython itself in
> a future release ;)

Let's get this rolling sooner rather than later. :)  Would you mind opening an issue on bugs.python.org?

**Comment by DonJayamanne** [comment] 2018-07-11 17:40
@fabioz 
Understood, lets leave this alone for the moment.
Please could you check https://github.com/Microsoft/ptvsd/issues/581 as that's related to this issue.

**Comment by fabioz** [comment] 2018-07-11 18:10
>> Ideally Python itself would provide the return event with an exception
>>    arg, but it doesn't... maybe something nice to add to CPython itself in
>>    a future release ;)
> 
> Let's get this rolling sooner rather than later. :) Would you mind opening an issue on bugs.python.org?

Created: https://bugs.python.org/issue34099 (actually, the arg in the 'return' already has a usage, so, it'd need to be a new event or add it to the frame itself).

**Comment by fabioz** [comment] 2018-07-11 18:10
> @fabioz
> Understood, lets leave this alone for the moment.
> Please could you check #581 as that's related to this issue.

Will take a look at it.

**Comment by DonJayamanne** [comment] 2018-07-31 00:35
@fabioz 
> @DonJayamanne if you want I can still use sys.excepthook for the main thread -- which as I mentioned is what was used before, but still, this isn't ideal and the user could break it if it reassigned it (which is actually pretty common

Can't we monkey patch `sys.excepthook`?

/cc @karthiknadig

**Comment by fabioz** [comment] 2018-07-31 11:36
> 
> Can't we monkey patch sys.excepthook?
> 

I don't think we can do that in simple way as the user can always reassign it at any point in his program -- and that's actually common (some users had already complained on that approach).

Not that it's impossible (just wouldn't be such a simple solution)... The ways I see doing that would be wrapping the whole sys module and putting a new version on the original sys.modules so that when the user assigns its own version we can wrap it in the __setattribute__ (still not ideal because some users do reload sys and put a new version on sys.modules) or by continually re-checking it during the tracing to reassign our own version which would call the users version and then ours.

The second approach would probably be preferred (we could check it only in the situations we know could lead to exiting the program as we do now, but instead of doing that we'd change the sys.excepthook), but the real problem here is that this won't solve the issue on uncaught exceptions on other threads, where there's no such hook.

My current idea is trying to solve this one by looking at the bytecode of the function as is done by setting `frame.f_lineno` ... it may be a bit more complex, but I think it would be more reliable and would cover all the use cases (I have a few items to look first thought... current plan is #697, #679, #253, #45 and then this one, but let me know if it you'd like me to reorder priorities).

**Comment by DonJayamanne** [comment] 2018-07-31 14:30
> and then this one, but let me know if it you'd like me to reorder priorities

Thats fine. Thanks.

**Closed** 2018-09-24 20:28 UTC
Labels: bug, priority:P1, regression, upstream-pydevd
