### ISSUE TITLE
Ensure attach to pid is bitness agnostic

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/ptvsd#1624] opened 2019-07-24 21:47 UTC

**Comment by fabioz** [comment] 2019-08-12 10:59
@int19h 

Karthik mentioned you could give some details on how this was fixed in the mixed mode debugger (i.e.: attach to 32 bit process from a 64 bit process and vice-versa)... can you share those here?

**Comment by int19h** [comment] 2019-08-12 18:49
It's not just a mixed-mode debugger thing, actually. It's the original implementation of Attach to Process in VS for the old version of ptvsd. It is not directly reusable, because the implementation constraints there were very different. But we can reuse the basic principle.

The gist of the problem is that you can't call `CreateRemoteThread` from a 32-bit process, if the target is a 64-bit process. So then, when bitness doesn't match, the 32-bit process needs to spawn a 64-bit helper process, the sole purpose of which is invoking `CreateRemoteThread`.

In VS, this was easy, because the code that called `CreateRemoteThread` was written in C#. So we simply compiled two versions of that assembly, with different bitness. VS referenced the 32-bit version, since it's 32-bit itself. That one checked the bitness of the target process, and if it was also 32-bit, then it proceeded with `CreateRemoteThread`. If it was 64-bit, then it started itself as a separate process (since managed assemblies can work both as executables and as libraries), passing all the necessary data via command line - and the 64-bit process then performed the thread injection.

In our case, the code that does the thread injection is written in Python, so it's not quite as easy. I think we'll need to rewrite the code that does `CreateRemoteThread` as a C++ app - then we can also compile it with different bitness as needed. It can be a very small app - the Python side can handle all the heavy lifting in locating the actual DLL we'll be injecting etc, and then pass everything as command line args.

And then on Win32, I wouldn't even bother special-casing same bitness to use the existing code. Just determine the target bitness, and use the appropriate native helper for injection in all cases - it's one extra process, but it's a one-off thing, and very lightweight.

**Comment by int19h** [comment] 2019-08-12 18:58
Looking at the Python code that currently does the injection, I think we can drastically simplify that as well. There's DLL injection proper, and then it generates a bunch of code to call a function in the loaded DLL.

A simpler approach would be to do it like this:

1. `CreateRemoteThread` with `LoadLibrary` as target, to inject our DLL.
2. DLL starts *another* thread first thing in `DllMain`. That thread is no longer running under DLL loader lock, so it can do whatever it want.
4. That new thread calls `AttachAndRunPythonCode`.

The original attach code in VS didn't even bother with the new thread - it just did everything directly from `DllMain`. But the code in pydevd is somewhat different, so I'm not sure it's entirely safe in that regard... in any case, we might as well just play it safe.

**Comment by fabioz** [comment] 2019-08-12 19:04
I like that idea... it really goes through many hoops to call the function to attach and this should really simplify things.

I'll take a look at this when I finish the hooking of native threads (#305).

**Comment by int19h** [comment] 2019-08-12 19:23
The only tricky part is communication with the injected code, since you can no longer pass function arguments to it. But since both sides are in native code with this approach - both the one that calls `CreateRemoteThread`, and the one in `DllMain` and the thread it spawns - they can use whatever Win32 IPC mechanism is most convenient for this.

The original VS implementation used [named shared memory](https://docs.microsoft.com/en-us/windows/win32/memory/creating-named-shared-memory) (basically a memory-mapped file with no disk backing) - mostly because C# has a convenient high-level API for this. This is probably still the easiest - more so than e.g. named pipes, because you need to manage connection lifetime there. 

We could also use `CoRegisterClassObject(CLSCTX_LOCAL_SERVER)` to have our injected DLL basically expose a COM endpoint from within the process, which the injector could then access via `CoGetClassObject` - and let COM take care of all the remoting, data marshaling etc. This would be much higher-level, and allow fancier communication between the two, e.g. callbacks. But for this scenario, where we really just need to pass data in, let it run, and get data (error code and message) out, shared memory should still be easier.

**Comment by karthiknadig** [comment] 2019-11-01 16:47
@fabioz I think this should be the next item to address after addressing multiproc related stuff. This is needed so we can deprecate ptvsd==3.*

**Comment by fabioz** [comment] 2019-11-04 11:38
I'll start taking a look at it.

**Comment by fabioz** [comment] 2019-11-07 19:25
Just to note, my plan is to provide a pull request for this on Monday.

**Closed** 2019-11-18 18:37 UTC
Labels: Enhancement, Upstream-pydevd, area:Native
