### ISSUE TITLE
Can't import cv2

### ISSUE THREAD

**Issue by FenryrMKIII** [microsoft/ptvsd#1913] opened 2019-11-14 07:42 UTC
Issue Type: <b>Bug</b>

# Create an environment with Python 3.8.0
In an Anaconda prompt, type 
`conda create -n myEnv python=3.8`
# install opencv using conda.
In an Anaconda prompt, type 
`conda install -c conda-forge opencv`
# Launch visual studio code 
`code .`
# Import opencv in a `python.py` script
`import cv2`

# Launch script using visual studio debugger with following config :

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "myPythonScript",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "internalConsole"
        }
    ]
}
```

Visual studio will not raise any error or anything but will not execute the code. The mistake has been identified as being caused by cv2 by putting a breakpoint and manually typing import cv2 in the debugger window

Importing cv2 in anaconda prompt works flawlessly

Extension version: 2019.10.44104
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.04GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment] 2019-11-20 22:13
The problem is that it can't import MKL:
```
INTEL MKL ERROR: The specified module could not be found. mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
```
This, in turn, is because it's not running from an activated Conda environment, e.g. via `conda run`. There's an existing issue tracking that work: https://github.com/microsoft/vscode-python/issues/8422 - closing this one as a dupe.

**Closed by int19h** 2019-11-20 22:13 UTC
