### ISSUE TITLE
When running on arm: OSError: Error relocating attach_linux_x86.so unsupported relocation type 7

### ISSUE THREAD

**Issue by pvizeli** [microsoft/ptvsd#1666] opened 2019-08-08 07:19 UTC
## Environment data

- PTVSD version: 4.3.0
- OS and version: Alpine 3.10
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3
- Using VS Code or Visual Studio: VSCode

## Actual behavior

If I start the debuger with `ptvsd.enable_attach(address=("0.0.0.0", 33333), redirect_output=True)`, I see follow trace on my log:

```
Error loading: /usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_linux_x86.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd_tracing.py", line 146, in load_python_helper_lib
    lib = ctypes.pydll.LoadLibrary(filename)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: Error relocating /usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_linux_x86.so: unsupported relocation type 7
```

## Expected  behavior

No trace in my log

## Steps to reproduce:

1. Use ptvsd on docker with python:3.7-alpine

**Comment by int19h** [comment] 2019-08-08 08:10
What architecture is it running on?

If it's x64, is it 64-bit-only (i.e. no lib32 etc)?

**Comment by pvizeli** [comment] 2019-08-08 08:46
In that case, it's an armv6 and the other instance was an armv7.

I see the "issue" with https://github.com/home-assistant/hassio and the latest ptvsd update.

**Comment by int19h** [comment] 2019-08-08 09:29
@fabioz, looks like the new tracing code in pydevd_tracing.py assumes Intel? We might want to build ARM binaries in the future, but either way, it needs to check for architecture somehow. Looks like this is not easy in portable Python, so it might be easiest to just try to load it, and see if that works? 

Or perhaps we can use the same naming convention as wheels for those binaries? i.e. consistently use `platform.machine()` - so it would have to be `x86_64` rather than `amd64` on  Linux, for example. Then it can avoid bitness checks, and just construct the name and check if it exists.

**Comment by fabioz** [comment] 2019-08-08 10:44
@int19h 
Yes, Intel is assumed... 

As a note, that dll could be optional (so, handling the exception and proceeding would be almost ok -- things that wouldn't work in this case would be the attach to pid and tracing all threads when an attach happens).

@pvizeli can you try to compile that dll locally to check if it works? i.e.: 

```
cd /usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/linux_and_mac
g++ -m32 -shared -o attach_linux_x86.so -fPIC -nostartfiles attach.cpp
mv attach_linux_x86.so ../attach_linux_x86.so
```

**Comment by fabioz** [comment] 2019-08-08 10:52
@int19h
Actually, that exception appears in the log but the debugger should work properly already (with the caveats I mentioned earlier), as that exception is handled (and printed) so, just printing the exception if the trace level is higher would be the first step here (and we can provide pre-compiled dlls for arm as a second step).

@pvizeli 
This means that locally you can just open the file `/usr/local/lib/python3.7/site-packages/ptvsd/_vendored/pydevd/pydevd_tracing.py` and comment line 149 -- with the contents: `pydev_log.exception('Error loading: %s', filename)` to work around it (i.e.: stop printing the exception) -- if you're not able to compile it locally.

**Comment by int19h** [comment] 2019-08-08 18:36
Yep, if it basically works, just without the new goodness - same as on older versions of Python - that's the expected behavior right now. It's the error message that is the issue.

Note that this will also affect various IoT scenarios, and potentially Windows on ARM (although I don't think there's official Python builds for that yet).

**Comment by fabioz** [comment] 2019-08-09 18:44
As I was working in the related code, I've also fixed the logging issue in the latest commit:
https://github.com/microsoft/ptvsd/commit/152edebd4e2b2859a23f1328bb8a2f640b6caf73#diff-5a4a91556d4ed2cc131c7fb1395c8f36R149

@int19h @karthiknadig 
Should this bug be left open to actually compile for arm in the future or can I close it?

**Comment by karthiknadig** [comment] 2019-08-09 19:39
@fabioz We need to make separate epic to create arm builds.

Closing this issue.

**Closed by karthiknadig** 2019-08-09 19:39 UTC

**Comment by pvizeli** [comment] 2019-08-11 08:28
Looks fine. Thanks for support
