### ISSUE TITLE
Debug console: `\n` not shown as new line (NumPy ndarray)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/ptvsd#1432] opened 2019-05-17 23:10 UTC
@yzhang-gh commented on [Fri May 17 2019](https://github.com/microsoft/vscode-python/issues/5672)

_Copied from microsoft/vscode#73845_

## Environment data

- VS Code version: 1.34.0
- Extension version (available under the Extensions sidebar): 2019.4.12954
- OS and version: Windows 10 build18898
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.1
- Relevant/affected Python packages and their versions: NumPy

## Expected behaviour

When evaluating a NumPy ndarray in the debug console, the `\n` should become a new line.

```
>>> import numpy as np
>>> a = np.arange(15).reshape(3, 5)
>>> a
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
```

## Actual behaviour

![image](https://user-images.githubusercontent.com/7588612/57884715-39c55b80-7821-11e9-81c2-6e5b776b062b.png)

## Steps to reproduce:

1. Start a debug session
2. Type `import numpy as np`
3. Type `np.random.rand(5, 5)`

**Comment by int19h** [comment] 2019-05-18 00:23
This happens for any object that has `repr()` with newlines (and also tabs). 

But this is a VSCode bug . When we send the variable value back, it's a JSON string literal, and `\n` in that literal is an escape character that must be deserialized as newline. For some reason, VSCode replaces any such newlines with a literal sequence `\n` *after* deserialization. It also does the same for `\t`, but not for e.g. `\f`. For example, this:

```py
class Foo(object):
    def __repr__(self):
        return 'foo\tbar\nbaz\fblah'
foo = Foo()
```

produces this in the log:

```json
{
    "name": "foo",
    "value": "foo\tbar\nbaz\fbah",
    "type": "Foo",
    "evaluateName": "foo",
    "variablesReference": 7
},
```

which is correct, but it is then rendered like so in Variables:

![image](https://user-images.githubusercontent.com/1175142/57962056-33d68580-78c8-11e9-928d-ac411d86cca8.png)

Given the difference in treatment, this is likely intentional.

**Comment by yzhang-gh** [comment] 2019-05-18 00:33
> But this is a VSCode bug ...

cc @isidorn

**Comment by isidorn** [comment] 2019-05-23 08:06
Yeah this is intentional, we use \n and \t in the variables view to save on space. If you think this is wrong please file a new feature request against vscode and argue for your case. Thanks

**Comment by fabioz** [comment] 2019-05-23 10:50
@isidorn the issue happens in the debug console, not in the variables view (it makes sense in the variables view for me as the space is really limited but seems strange in the debug console where the user is evaluating probably because he couldn't see very well in the variables view).

The issue was already reported to VSCode (https://github.com/microsoft/vscode/issues/73845) and was moved here because it was marked as `caused-by-extension`, but as that doesn't seem to be the case. I'll add more info to that issue and close this one as it doesn't seem to be caused by the extension.

**Comment by yzhang-gh** [comment] 2019-05-23 22:00
Thank you all!

**Comment by rbu** [comment] 2019-11-03 21:07
@isidorn @yzhang-gh @int19h The issue on vscode (microsoft/vscode#73845) was closed as out of scope and was refered back to this extension. Could you reopen this bug as a consequence?

The current state makes the debug console unusable for any multiline strings (such as tabluar data). I see the space optimization point for the Variables view, but the console should use the horizontal space it has available (like any other terminal).

To give you an example, I'm trying to make sense of this "table".
![image](https://user-images.githubusercontent.com/65913/68091946-4d738580-fe86-11e9-8d9e-1b07acb849c4.png)

**Comment by fabioz** [comment] 2019-11-04 11:27
Well, as it stands, the only way I can see here would be not returning a `frameReference` and just print the result instead (i.e.: when the user does `np.random.rand(5, 5)`, instead of returning the variable we'd return nothing and would print it instead).

 -- note that right now the workaround is doing the print yourself: 

i.e.: Instead of doing: 

`np.random.rand(5, 5)`

you can do:

`print(np.random.rand(5, 5))`

the downside is that it won't be expandable/collapsible, but without the change in https://github.com/microsoft/vscode/issues/73845, the extension is powerless to decide how it wants `variableReferences` to be shown in the debug console (see my comment at https://github.com/microsoft/vscode/issues/73845#issuecomment-495909283).

**Comment by int19h** [comment] 2019-11-04 19:19
We need changes from VSCode to fix this properly, and we'll ask for them. But until then, it still manifests as a product bug in the debugger, so we'll track that here.

**Comment by luabud** [comment] 2020-01-22 21:18
Upstream  issue: https://github.com/microsoft/vscode/issues/89114

**Comment by ychechik** [comment] 2020-02-23 14:57
@luabud This is now solved upstream: https://github.com/microsoft/vscode/issues/73845#issuecomment-582458652

**Closed** 2020-04-23 22:46 UTC
Labels: Bug
